/* GENERATED by tools/gen-canton-design.py from the approved design draft (docs/design/src) — do not edit by hand.
   西關大屋: every prop, sign, shop front, tree and the town outside is built by the draft's own code, so the game shows what was approved.
   Left to the game: the blocks people stand on and ink (ground, walls, slopes) — it draws those with the draft's textures. */
/* 西关骑楼街 · CANTON ARCADE — layout data (design draft v1)
   Units: metres. x = across (±26), z = along (±52). Team 0 (orange) spawns at +z, team 1 at -z.
   Only team 0's half is listed (plus pieces marked self:true that already sit on the centre);
   the other half is the same list rotated 180° round the centre, like the skatepark.
   Heights: canal bed -1.8 · street 0 · low cover 0.5 / 1.0–1.2 · shop 2.4 · spawn roof 2.0 ·
   大屋 wings 2.6 · arcade roof 3.0 · ancestral hall roof 4.0
   Engine mapping: box / ramp = existing solids; float = NEW "solid with an underside" (people walk
   under it, bump their head on it); fence = existing grate fence (squids pass, people don't);
   oob = existing out-of-bounds block; canal = existing height-field terrain (sunken band).      */
const GZ = (() => {
  const XH = 26, ZH = 52;
  const CANAL = { z0: -3.5, z1: 3.5, bed: -2.2, shallow: -2.0, deep: -0.6 };
  const B = (x0, x1, z0, z1, h, kind, o = {}) => Object.assign({ t: 'box', x0, x1, z0, z1, y0: 0, h, kind }, o);
  const R = (x0, x1, z0, z1, axis, h0, h1, kind, o = {}) => Object.assign({ t: 'ramp', x0, x1, z0, z1, axis, h0, h1, y0: 0, kind }, o);
  const F = (x0, x1, z0, z1, y0, h, kind, o = {}) => Object.assign({ t: 'box', x0, x1, z0, z1, y0, h, kind, float: true }, o);

  const half = [
    // ---- spawn: the tea house's roof terrace (red quarry tiles), stairs down to the street
    B(-10, 10, 42, 52, 2.0, 'terrace', { zone: 'spawn', label: '茶楼天台（出生点）' }),
    R(-3, 3, 36, 42, 'z', 0, 2.0, 'stair', { zone: 'spawn', label: '下街石阶' }),
    B(10, 26, 42, 52, 2.0, 'terrace', { zone: 'spawn', label: '天台' }),
    B(15, 17, 46, 48, 3.6, 'tank', { zone: 'spawn', label: '水箱' }),
    B(-26, -10, 44, 52, 9.0, 'teahouse', { oob: true, zone: 'spawn', label: '茶樓（陶陶居 / 蓮香樓）' }),
    R(20.3, 26, 36, 42, 'z', 3.8, 2.0, 'terrace', { zone: 'arcade', label: '上骑楼坡道' }),

    // ---- qilou arcade along the +x wall: covered street below, walkable upper deck above
    F(20.3, 26, 8, 36, 3.4, 3.8, 'arcade', { zone: 'arcade', label: '骑楼二层走廊', isNew: true }),
    F(20.3, 20.6, 8, 36, 3.8, 4.7, 'balustrade', { zone: 'arcade' }),

    // ---- Xiguan mansion along the -x wall: two flat-roof wings, a courtyard behind a tanglong gate
    B(-26, -15, 12, 16, 2.6, 'brick', { zone: 'mansion', label: '大屋南翼（天台）' }),
    B(-26, -15, 30, 34, 2.6, 'brick', { zone: 'mansion', label: '大屋北翼（天台）' }),
    B(-26, -23, 16, 30, 4.4, 'hall', { oob: true, zone: 'mansion', label: '正厅' }),
    B(-16, -15, 16, 21, 2.6, 'brick', { zone: 'mansion' }),
    B(-16, -15, 25, 30, 2.6, 'brick', { zone: 'mansion' }),
    // (v3: the gate is open — no tanglong fence; people walk in under the lintel)
    F(-16, -15, 21, 25, 2.2, 2.6, 'lintel', { zone: 'mansion', label: '門楣（下面是敞開的大門）' }),
    R(-15, -10, 30, 34, 'x', 2.6, 0, 'stair', { zone: 'mansion', label: '外楼梯' }),
    B(-20.5, -18, 21, 25, 1.0, 'planterbox', { zone: 'mansion', label: '天井花台' }),
    R(-15, -10, 12.4, 16, 'x', 2.6, 0, 'stair', { zone: 'mansion', label: '外楼梯' }),

    // ---- the street between them
    B(-11, -5, 18, 25, 2.4, 'shop', { zone: 'street', label: '小樓（吳系茶餐廳 / 廣州酒家）' }),
    B(-5, -3.5, 18, 19.6, 1.2, 'steamer', { zone: 'street', label: '蒸笼堆' }),
    B(-1, 0.6, 14, 15.6, 0.5, 'steamer', { zone: 'street' }),
    B(5, 11, 13, 18, 0.5, 'planter', { zone: 'street', label: '榕树花基' }),
    B(2, 5, 25, 26.6, 1.1, 'stall', { zone: 'street', label: '街邊檔' }),
    B(13, 15, 24, 26.5, 1.2, 'trike', { zone: 'street', label: '三轮车' }),
    B(14, 17, 16, 17, 1.0, 'planterwall', { zone: 'street', label: '花基矮墙' }),
    B(-4.4, -3.6, 30.6, 31.4, 4.6, 'post', { zone: 'street' }),
    B(3.6, 4.4, 30.6, 31.4, 4.6, 'post', { zone: 'street' }),
    F(-5, 5, 30.5, 31.5, 3.4, 4.6, 'lintel', { zone: 'street', label: '獵德牌坊' }),

    // ---- canal-side promenade: kapok trees, stone landing steps down into the canal
    B(-7, -5, 6, 8, 0.5, 'planter', { zone: 'canal', label: '木棉' }),
    B(10, 12, 5.5, 7.5, 0.5, 'planter', { zone: 'canal', label: '木棉' }),
    B(-12, -11.2, 1.7, 3.5, -0.45, 'landing', { y0: -1.8, zone: 'canal', label: '埠头' }),
    B(-11.2, -10.4, 1.7, 3.5, -0.9, 'landing', { y0: -1.8, zone: 'canal' }),
    B(-10.4, -9.6, 1.7, 3.5, -1.35, 'landing', { y0: -1.8, zone: 'canal' }),
    B(22.2, 23, 1.7, 3.5, -0.45, 'landing', { y0: -1.8, zone: 'canal', label: '埠头' }),
    B(21.4, 22.2, 1.7, 3.5, -0.9, 'landing', { y0: -1.8, zone: 'canal' }),
    B(20.6, 21.4, 1.7, 3.5, -1.35, 'landing', { y0: -1.8, zone: 'canal' }),
    // stone arch bridge (one half of it; the rotated copy is the other side bridge)
    R(14, 18, 0, 5.5, 'z', 0.8, 0, 'bridge', { float: true, thick: 0.5, zone: 'canal', label: '石拱桥', isNew: true }),
    R(14, 18, -5.5, 0, 'z', 0, 0.8, 'bridge', { float: true, thick: 0.5, zone: 'canal' }),

    // ---- centre: the ancestral hall stands on a square deck over the canal
    B(2.5, 5, -2.5, 0, 2.0, 'citywall', { zone: 'centre', label: '城牆台（2 米）' }),
    B(2.5, 5, -4.2, -2.5, 1.0, 'citywall', { zone: 'centre' }),
    // dragon boat moored in the canal (walkable deck, a jump up from the canal bed)
    B(8.5, 19, 0.2, 1.4, -1.5, 'boat', { y0: -2.2, zone: 'canal', label: '龍舟' }),
  ];
  // arcade columns: 8 per side, ~3.3 m between them
  for (let i = 0; i < 8; i++) { const c = 8.3 + i * (35.7 - 8.3) / 7; half.push(B(20.3, 20.9, c - 0.3, c + 0.3, 3.4, 'column', { zone: 'arcade' })); }

  const centre = [
    F(-7, 7, -3.5, 3.5, -0.8, 0, 'deck', { zone: 'centre', label: '中央广场桥（桥下只能鱿鱼过）', isNew: true }),
    B(-2.5, 2.5, -2.5, 2.5, 4.0, 'zhl', { zone: 'centre', label: '鎮海樓（4 米平台）' }),
    B(-1, 1, -1, 1, 8.2, 'zhltop', { zone: 'centre', label: '鎮海樓上層' }),
  ];
  const trees = [
    { kind: 'banyan', x: 8, z: 15.5, y: 0.5, r: 0.7, k: 1.0 },
    { kind: 'kapok', x: -6, z: 7, y: 0.5, r: 0.35, k: 1.0 },
    { kind: 'kapok', x: 11, z: 6.5, y: 0.5, r: 0.35, k: 0.9 },
  ];
  const rot = s => {
    const m = Object.assign({}, s, { x0: -s.x1, x1: -s.x0, z0: -s.z1, z1: -s.z0, team: 1 });
    if (s.t === 'ramp') { m.h0 = s.h1; m.h1 = s.h0; }
    return m;
  };
  const solids = [];
  half.forEach(s => { solids.push(Object.assign({ team: 0 }, s)); solids.push(rot(s)); });
  centre.forEach(s => solids.push(Object.assign({ self: true }, s)));
  const allTrees = [];
  trees.forEach(t => { allTrees.push(t); allTrees.push(Object.assign({}, t, { x: -t.x, z: -t.z })); });
  const spawns = [{ x: 0, z: 47, y: 2, yaw: Math.PI, team: 0 }, { x: 0, z: -47, y: 2, yaw: 0, team: 1 }];
  return { XH, ZH, CANAL, solids, trees: allTrees, spawns, BODY_H: 1.7, STEP: 0.55, JUMP_V: 8.3, GRAV: 24, RUN: 6.4 };
})();


let GZT_;
function cantonGZT() { return GZT_ || (GZT_ = (() => {
/* procedural textures for the Canton Arcade preview (all drawn in code, like the game) */
return (() => {
  let seed = 7;
  const rnd = () => { seed |= 0; seed = seed + 0x6D2B79F5 | 0; let t = Math.imul(seed ^ seed >>> 15, 1 | seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; };
  const rr = (a, b) => a + (b - a) * rnd();
  const shade = (hex, k) => { const c = new THREE.Color(hex); c.offsetHSL(0, 0, k); return '#' + c.getHexString(); };
  function ctex(w, h, fn, srgb = true) {
    const c = document.createElement('canvas'); c.width = w; c.height = h;
    const g = c.getContext('2d'); fn(g, w, h);
    const t = new THREE.CanvasTexture(c); t.wrapS = t.wrapT = THREE.RepeatWrapping;
    if (srgb) t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 8; t.userData.canvas = c; return t;
  }
  const speckle = (g, w, h, n, a) => { for (let i = 0; i < n; i++) { g.fillStyle = `rgba(${rnd() < 0.5 ? '0,0,0' : '255,255,255'},${rr(0.02, a)})`; g.fillRect(rnd() * w, rnd() * h, rr(1, 3), rr(1, 3)); } };
  const T = {};
  // 麻石: long granite street slabs laid in running courses (one texture = 4 m)
  T.granite = ctex(512, 512, (g, w, h) => {
    g.fillStyle = '#b7b0a3'; g.fillRect(0, 0, w, h);
    const rows = 8, rh = h / rows;
    for (let r = 0; r < rows; r++) {
      let x = -rr(0, 120);
      while (x < w) { const L = rr(110, 220); g.fillStyle = shade('#b9b2a5', rr(-0.05, 0.04)); g.fillRect(x + 2, r * rh + 2, L - 4, rh - 4); x += L; }
    }
    speckle(g, w, h, 9000, 0.12);
    g.strokeStyle = 'rgba(70,64,56,.55)'; g.lineWidth = 2.5;
    for (let r = 0; r <= rows; r++) { g.beginPath(); g.moveTo(0, r * rh); g.lineTo(w, r * rh); g.stroke(); }
  });
  // lighter dressed granite for bridges, the paifang, plinths
  T.stone = ctex(256, 256, (g, w, h) => {
    g.fillStyle = '#d7d1c4'; g.fillRect(0, 0, w, h);
    for (let r = 0; r < 4; r++) for (let c = 0; c < 2; c++) { g.fillStyle = shade('#d6d0c3', rr(-0.04, 0.03)); g.fillRect(c * 128 + (r % 2) * 64 - 64 + 2, r * 64 + 2, 124, 60); g.fillRect(c * 128 + (r % 2) * 64 + 192 + 2 - 256, r * 64 + 2, 124, 60); }
    speckle(g, w, h, 4000, 0.1);
    g.strokeStyle = 'rgba(90,84,76,.4)'; g.lineWidth = 2; for (let r = 0; r <= 4; r++) { g.beginPath(); g.moveTo(0, r * 64); g.lineTo(w, r * 64); g.stroke(); }
  });
  // canal wall: big rough granite blocks, damp and mossy toward the water
  T.canal = ctex(512, 256, (g, w, h) => {
    g.fillStyle = '#8a857a'; g.fillRect(0, 0, w, h);
    for (let r = 0; r < 4; r++) { let x = -rr(0, 80); while (x < w) { const L = rr(70, 150); g.fillStyle = shade('#8b867b', rr(-0.06, 0.05)); g.fillRect(x + 3, r * 64 + 3, L - 6, 58); x += L; } }
    speckle(g, w, h, 5000, 0.15);
    const gr = g.createLinearGradient(0, 0, 0, h); gr.addColorStop(0, 'rgba(0,0,0,0)'); gr.addColorStop(0.55, 'rgba(40,60,40,.15)'); gr.addColorStop(1, 'rgba(40,70,45,.55)'); g.fillStyle = gr; g.fillRect(0, 0, w, h);
  });
  // 青砖: grey-blue water-polished bricks with thin light mortar (texture = 2 m)
  T.brick = ctex(512, 512, (g, w, h) => {
    g.fillStyle = '#9b9d97'; g.fillRect(0, 0, w, h);
    const bw = 64, bh = 20;
    for (let r = 0; r < h / bh; r++) for (let c = -1; c < w / bw + 1; c++) {
      const x = c * bw + (r % 2) * bw / 2; g.fillStyle = shade('#69737a', rr(-0.05, 0.05)); g.fillRect(x + 1.5, r * bh + 1.5, bw - 3, bh - 3);
    }
    speckle(g, w, h, 6000, 0.08);
  });
  // 阶砖: red quarry tiles on roof terraces (texture = 2.4 m, 30 cm tiles)
  T.terrace = ctex(256, 256, (g, w, h) => {
    g.fillStyle = '#c9b9a4'; g.fillRect(0, 0, w, h);
    const n = 8, s = w / n;
    for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) { g.fillStyle = shade('#b4553c', rr(-0.06, 0.05)); g.fillRect(i * s + 1.5, j * s + 1.5, s - 3, s - 3); }
    speckle(g, w, h, 3000, 0.1);
  });
  // 瓦: grey pan-and-roll roof tiles
  T.tiles = ctex(256, 256, (g, w, h) => {
    g.fillStyle = '#5d6266'; g.fillRect(0, 0, w, h);
    for (let x = 0; x < w; x += 16) { const gr = g.createLinearGradient(x, 0, x + 16, 0); gr.addColorStop(0, '#4b5054'); gr.addColorStop(0.5, '#8a9095'); gr.addColorStop(1, '#4b5054'); g.fillStyle = gr; g.fillRect(x, 0, 16, h); }
    for (let y = 0; y < h; y += 22) { g.fillStyle = 'rgba(0,0,0,.18)'; g.fillRect(0, y, w, 3); }
  });
  T.greenTiles = ctex(128, 128, (g, w, h) => {
    for (let x = 0; x < w; x += 12) { const gr = g.createLinearGradient(x, 0, x + 12, 0); gr.addColorStop(0, '#1f6a4a'); gr.addColorStop(0.5, '#4fae7c'); gr.addColorStop(1, '#1f6a4a'); g.fillStyle = gr; g.fillRect(x, 0, 12, h); }
    for (let y = 0; y < h; y += 16) { g.fillStyle = 'rgba(0,0,0,.2)'; g.fillRect(0, y, w, 2); }
  });
  T.wood = ctex(128, 256, (g, w, h) => {
    g.fillStyle = '#6e3220'; g.fillRect(0, 0, w, h);
    for (let i = 0; i < 70; i++) { g.strokeStyle = `rgba(${rnd() < 0.5 ? '30,10,5' : '150,80,50'},${rr(0.05, 0.25)})`; g.lineWidth = rr(1, 3); g.beginPath(); const x = rnd() * w; g.moveTo(x, 0); g.bezierCurveTo(x + rr(-8, 8), h / 3, x + rr(-8, 8), h * 2 / 3, x + rr(-6, 6), h); g.stroke(); }
  });
  T.bamboo = ctex(128, 64, (g, w, h) => { g.fillStyle = '#c9a463'; g.fillRect(0, 0, w, h); for (let x = 0; x < w; x += 6) { g.fillStyle = `rgba(90,60,20,${rr(0.1, 0.3)})`; g.fillRect(x, 0, 1.5, h); } g.fillStyle = '#8e6a32'; g.fillRect(0, 0, w, 6); g.fillRect(0, h - 6, w, 6); });
  // 满洲窗: coloured glass in a white lattice
  const MANCHU = ['#d8432f', '#2f6fc0', '#f0c419', '#3f9b55', '#e9e4d8'];
  const manchu = (g, x0, y0, w, h, n = 4, m = 4) => {
    g.fillStyle = '#5a2f1c'; g.fillRect(x0, y0, w, h);
    const fr = Math.max(2, Math.min(w, h) * 0.03), cw = (w - fr) / n, ch = (h - fr) / m;
    for (let i = 0; i < n; i++) for (let j = 0; j < m; j++) {
      const ex = i === 0 || i === n - 1, ey = j === 0 || j === m - 1;
      g.fillStyle = ex && ey ? '#c53a2b' : ex ? '#2f66b0' : ey ? '#3a8f55' : (i + j) % 2 ? '#dfe9e6' : '#e9c64a';
      if (!ex && !ey && (i + j) % 2 === 0) g.globalAlpha = 0.85;
      g.fillRect(x0 + fr + i * cw, y0 + fr + j * ch, cw - fr, ch - fr); g.globalAlpha = 1;
      if (!ex && !ey) { g.strokeStyle = 'rgba(90,47,28,.55)'; g.lineWidth = 1; g.beginPath(); const cx = x0 + fr + i * cw + (cw - fr) / 2, cy = y0 + fr + j * ch + (ch - fr) / 2; g.moveTo(cx, cy - (ch - fr) / 2); g.lineTo(cx + (cw - fr) / 2, cy); g.lineTo(cx, cy + (ch - fr) / 2); g.lineTo(cx - (cw - fr) / 2, cy); g.closePath(); g.stroke(); }
    }
    g.fillStyle = 'rgba(255,255,255,.12)'; g.fillRect(x0, y0, w, h * 0.3);
  };
  T.manchu = ctex(256, 256, (g, w, h) => { manchu(g, 0, 0, w, h, 6, 6); });
  // a qilou bay facade: 4 m wide, 12.8 m tall (shopfront, two upper floors with tall windows, decorated parapet)
  const FAC = [
    { base: '#ead7a6', trim: '#fbf4e1', shut: '#3d7f5a' },
    { base: '#e9b9ac', trim: '#fff3ec', shut: '#2f6b85' },
    { base: '#b9d9c2', trim: '#f4fbf5', shut: '#7a4a2a' },
    { base: '#efe7d6', trim: '#ffffff', shut: '#386e9a' },
    { base: '#bccfe1', trim: '#f6fafd', shut: '#3b6f4f' },
    { base: '#e4a670', trim: '#fff1e2', shut: '#2c5c74' },
    { base: '#a8573f', trim: '#e9dcc8', shut: '#2f5a43', brick: true },
    { base: '#d9d3c6', trim: '#fbfaf6', shut: '#8a3b2b' },
  ];
  const SHOPS = ['藥材', '金舖', '打銅', '綢緞', '茶莊', '當舖', '鐘錶', '香燭', '玉器', '海味', '鞋莊', '書局'];
  T.facade = FAC.map((f, k) => ctex(256, 820, (g, w, h) => {
    const px = w / 4; // pixels per metre
    const Y = m => h - m * px;
    g.fillStyle = f.base; g.fillRect(0, 0, w, h);
    if (f.brick) { for (let r = 0; r < h / 6; r++) for (let c = -1; c < w / 16 + 1; c++) { g.fillStyle = shade(f.base, rr(-0.06, 0.05)); g.fillRect(c * 16 + (r % 2) * 8 + 0.5, r * 6 + 0.5, 15, 5); } }
    speckle(g, w, h, 2500, 0.07);
    // pilasters
    g.fillStyle = f.trim; g.fillRect(0, Y(12.2), 14, 12.2 * px - 4.4 * px); g.fillRect(w - 14, Y(12.2), 14, 12.2 * px - 4.4 * px);
    // floor bands / cornices
    [[4.4, 0.35], [7.8, 0.25], [11.2, 0.4]].forEach(([y, t]) => { g.fillStyle = f.trim; g.fillRect(0, Y(y + t), w, t * px); g.fillStyle = 'rgba(0,0,0,.18)'; g.fillRect(0, Y(y), w, 3); });
    // parapet: baroque pediment or balustrade
    if (k % 2 === 0) { g.fillStyle = f.trim; g.beginPath(); g.moveTo(10, Y(11.6)); g.quadraticCurveTo(w / 2, Y(13.6), w - 10, Y(11.6)); g.lineTo(w - 10, Y(11.2)); g.lineTo(10, Y(11.2)); g.fill(); g.fillStyle = f.base; g.beginPath(); g.arc(w / 2, Y(11.75), 0.35 * px, 0, Math.PI * 2); g.fill(); }
    else { for (let x = 18; x < w - 18; x += 14) { g.fillStyle = f.trim; g.fillRect(x, Y(12.3), 8, 0.9 * px); } g.fillRect(10, Y(12.5), w - 20, 6); }
    // upper windows with manchu fanlights and louvred shutters
    [4.9, 8.3].forEach(y0 => {
      [0.55, 2.35].forEach(x0 => {
        const X = x0 * px, W = 1.1 * px, H = 2.5 * px, top = Y(y0 + 2.5);
        g.fillStyle = f.trim; g.fillRect(X - 5, top - 5, W + 10, H + 10);
        g.fillStyle = '#26303a'; g.fillRect(X, top + 0.8 * px, W, H - 0.8 * px);
        manchu(g, X, top, W, 0.8 * px, 3, 2);
        g.fillStyle = f.shut; for (let s = 0; s < 2; s++) { const sx = s ? X + W * 0.62 : X; g.fillRect(sx, top + 0.85 * px, W * 0.38, H - 0.85 * px); g.fillStyle = 'rgba(0,0,0,.25)'; for (let l = 0; l < 14; l++) g.fillRect(sx, top + 0.95 * px + l * 6, W * 0.38, 1.5); g.fillStyle = f.shut; }
      });
      g.fillStyle = 'rgba(30,30,30,.85)'; for (let x = 0.4 * px; x < w - 0.4 * px; x += 7) g.fillRect(x, Y(y0 + 0.9), 2, 0.9 * px); g.fillRect(0.4 * px, Y(y0 + 0.95), w - 0.8 * px, 3);
    });
    // shopfront
    g.fillStyle = '#2a2622'; g.fillRect(16, Y(3.4), w - 32, 3.4 * px);
    g.fillStyle = 'rgba(255,214,140,.45)'; g.fillRect(24, Y(3.0), w - 48, 2.2 * px);
    g.fillStyle = '#3a312a'; for (let x = 24; x < w - 24; x += 18) g.fillRect(x, Y(3.0), 3, 2.2 * px);
    g.fillStyle = '#1d2a22'; g.fillRect(16, Y(4.25), w - 32, 0.75 * px);
    g.fillStyle = '#f2d27a'; g.font = `900 ${0.5 * px}px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC","STSong",serif`; g.textAlign = 'center'; g.textBaseline = 'middle';
    g.fillStyle = '#c9b06a'; g.fillRect(w / 2 - 34, Y(3.9), 68, 3);
  }));
  // inner arcade wall: shopfronts under the colonnade (texture = 8 m wide, 2.6 m tall)
  T.shopfront = ctex(1024, 340, (g, w, h) => {
    g.fillStyle = '#e8dcc2'; g.fillRect(0, 0, w, h);
    for (let i = 0; i < 2; i++) {
      const x = i * w / 2 + 30, W = w / 2 - 60;
      g.fillStyle = '#2a2420'; g.fillRect(x, 70, W, h - 70);
      g.fillStyle = 'rgba(255,205,120,.5)'; g.fillRect(x + 14, 90, W - 28, h - 110);
      g.fillStyle = '#5b2d1e'; for (let b = 0; b < 9; b++) g.fillRect(x + 6, 100 + b * 26, W - 12, 7);
      g.fillStyle = '#1e3326'; g.fillRect(x, 12, W, 52);
      g.fillStyle = '#f4d27d'; g.font = '900 38px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC",serif'; g.textAlign = 'center'; g.textBaseline = 'middle';
      g.fillText(['泼泼凉茶', '飞溅糖水', '墨记云吞', '浪记烧腊'][i + (rnd() < 0.5 ? 0 : 2)], x + W / 2, 40);
    }
  });
  // vertical shop sign
  T.sign = (text, bg = '#1e3326', fg = '#f4d27d') => ctex(96, 96 * Math.max(3, text.length) * 0.9, (g, w, h) => {
    g.fillStyle = bg; g.fillRect(0, 0, w, h); g.strokeStyle = fg; g.lineWidth = 5; g.strokeRect(6, 6, w - 12, h - 12);
    g.fillStyle = fg; g.font = `900 ${w * 0.62}px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC","STSong",serif`; g.textAlign = 'center'; g.textBaseline = 'middle';
    const n = text.length; [...text].forEach((ch, i) => g.fillText(ch, w / 2, (i + 0.5) * h / n));
  });
  T.plaque = (text, bg = '#1b1b1f', fg = '#e6bf5a') => ctex(512, 160, (g, w, h) => {
    g.fillStyle = bg; g.fillRect(0, 0, w, h); g.strokeStyle = fg; g.lineWidth = 8; g.strokeRect(10, 10, w - 20, h - 20);
    let px = 96; g.font = `900 ${px}px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC","STSong",serif`; while (((g.measureText(text) || {}).width || 0) > w - 70 && px > 20) { px -= 4; g.font = `900 ${px}px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC","STSong",serif`; }
    g.fillStyle = fg; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText(text, w / 2, h / 2 + 4);
  });
  // big tea-house facade at the spawn ends
  T.teahouse = ctex(1024, 640, (g, w, h) => {
    g.fillStyle = '#e9d9b4'; g.fillRect(0, 0, w, h); speckle(g, w, h, 6000, 0.06);
    for (let fl = 0; fl < 3; fl++) for (let c = 0; c < 8; c++) {
      const x = 40 + c * 120, y = 70 + fl * 150; g.fillStyle = '#f8f0dc'; g.fillRect(x - 6, y - 6, 92, 122);
      manchu(g, x, y, 80, 110, 4, 5);
    }
    g.fillStyle = '#f8f0dc'; for (let y of [55, 205, 355, 505]) g.fillRect(0, y, w, 8);
    g.fillStyle = '#8a1f1a'; g.fillRect(260, 0, 500, 52); g.fillStyle = '#f6d36b'; g.font = '900 42px "Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC",serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('浪 花 茶 楼', w / 2, 28);
    g.fillStyle = '#2a2420'; g.fillRect(0, 520, w, 120); g.fillStyle = 'rgba(255,200,120,.5)'; for (let c = 0; c < 6; c++) g.fillRect(40 + c * 165, 545, 120, 80);
  });
  // ripple for the canal water
  T.water = ctex(256, 256, (g, w, h) => {
    g.fillStyle = '#4c8c84'; g.fillRect(0, 0, w, h);
    for (let i = 0; i < 260; i++) { g.strokeStyle = `rgba(${rnd() < 0.5 ? '210,240,230' : '20,60,60'},${rr(0.05, 0.22)})`; g.lineWidth = rr(1, 2.5); const x = rnd() * w, y = rnd() * h, L = rr(8, 40); g.beginPath(); g.moveTo(x, y); g.quadraticCurveTo(x + L / 2, y - rr(1, 4), x + L, y); g.stroke(); }
  });
  // ink splats for the paint-readability test (orange team 0 at +z, blue team 1 at -z), on a 52 x 104 canvas
  T.ink = (XH, ZH, mask) => ctex(512, 1024, (g, w, h) => {
    const toPx = (x, z) => [(x + XH) / (2 * XH) * w, (z + ZH) / (2 * ZH) * h];
    const blob = (x, z, r, col) => {
      const [px, pz] = toPx(x, z), pr = r / (2 * XH) * w; g.fillStyle = col; g.beginPath();
      const n = 14; for (let i = 0; i <= n; i++) { const a = i / n * Math.PI * 2, rr2 = pr * (0.7 + rnd() * 0.5); g[i ? 'lineTo' : 'moveTo'](px + Math.cos(a) * rr2, pz + Math.sin(a) * rr2); } g.fill();
      for (let i = 0; i < 5; i++) { g.beginPath(); g.arc(px + (rnd() - 0.5) * pr * 3, pz + (rnd() - 0.5) * pr * 3, pr * rr(0.1, 0.25), 0, Math.PI * 2); g.fill(); }
    };
    for (let i = 0; i < 520; i++) {
      const x = rr(-XH, XH), z = rr(-ZH, ZH); if (!mask(x, z)) continue;
      const t0 = z > 0 ? 0.72 : 0.3; blob(x, z, rr(0.6, 1.8), rnd() < t0 ? '#ff7a00' : '#3346ff');
    }
  });

  // ---------------- v2: real shops, each with its own frontage (texture = the whole shop, 2.6 m tall, 96 px per metre)
  const SERIF = '"Noto Serif CJK TC","Noto Serif CJK SC","Songti TC","Songti SC","STSong",serif';
  const SANS = '"Noto Sans CJK TC","Noto Sans CJK SC","PingFang TC","PingFang SC","Heiti TC",sans-serif';
  const txt = (g, t, x, y, px, col, font = SERIF, align = 'center', w = 900, maxW = 0) => { g.fillStyle = col; g.font = `${w} ${px}px ${font}`; if (maxW) { let k = 0; while (((g.measureText(t) || {}).width || 0) > maxW && k++ < 60) { px *= 0.95; g.font = `${w} ${px}px ${font}`; } } g.textAlign = align; g.textBaseline = 'middle'; g.fillText(t, x, y); };
  const vtxt = (g, t, x, y0, px, col, font = SERIF) => { [...t].forEach((c, i) => txt(g, c, x, y0 + (i + 0.5) * px * 1.08, px, col, font)); };
  const tiles = (g, x, y, w, h, s, c1, c2) => { for (let i = 0; i * s < w; i++) for (let j = 0; j * s < h; j++) { g.fillStyle = (i + j) % 2 ? c1 : c2; g.fillRect(x + i * s, y + j * s, Math.min(s, w - i * s) - 1, Math.min(s, h - j * s) - 1); } };
  const PXM = 96;
  const SHOPFACE = {
    // 黃振龍涼茶: open counter, a row of brass gourd urns, covered bowls, the price board of herbal teas
    hzl(g, w, h) {
      g.fillStyle = '#efe6c8'; g.fillRect(0, 0, w, h);
      g.fillStyle = '#0f5a3a'; g.fillRect(0, 0, w, 62); g.fillStyle = '#f2c230'; g.fillRect(0, 62, w, 5);
      txt(g, '黃振龍涼茶', w / 2, 33, 44, '#f6d443'); txt(g, '始創於一九四〇年代', w - 96, 36, 14, '#f6d443', SANS, 'center', 700);
      g.fillStyle = '#3a2a1c'; g.fillRect(20, 78, w - 40, 96);                          // shelf wall of herb drawers
      for (let i = 0; i < Math.floor((w - 60) / 30); i++) for (let j = 0; j < 3; j++) { g.fillStyle = '#6b4a2c'; g.fillRect(28 + i * 30, 84 + j * 30, 26, 26); g.fillStyle = '#d9b36a'; g.fillRect(38 + i * 30, 95 + j * 30, 6, 4); }
      g.fillStyle = '#0f5a3a'; g.fillRect(0, 174, w, 82); g.fillStyle = '#f2c230'; g.fillRect(0, 174, w, 6);   // counter
      for (let i = 0; i < 3; i++) { const x = 90 + i * (w - 180) / 2;                       // brass gourds
        const gr = g.createRadialGradient(x - 8, 135, 2, x, 140, 30); gr.addColorStop(0, '#ffe9a0'); gr.addColorStop(1, '#a8741c'); g.fillStyle = gr;
        g.beginPath(); g.arc(x, 150, 24, 0, 7); g.fill(); g.beginPath(); g.arc(x, 118, 15, 0, 7); g.fill(); g.fillRect(x - 4, 96, 8, 10); g.fillStyle = '#7a1d18'; g.fillRect(x - 12, 128, 24, 5); }
      for (let i = 0; i < Math.floor((w - 60) / 46); i++) { const x = 40 + i * 46; if (Math.abs((x - 90) % ((w - 180) / 2)) < 34) continue; g.fillStyle = '#fbfaf2'; g.beginPath(); g.ellipse(x, 168, 16, 7, 0, 0, 7); g.fill(); g.fillStyle = '#3b2412'; g.beginPath(); g.ellipse(x, 166, 12, 4, 0, 0, 7); g.fill(); g.fillStyle = 'rgba(200,230,240,.7)'; g.fillRect(x - 15, 158, 30, 3); }
      ['斑痧涼茶', '廿四味', '五花茶', '龜苓膏', '酸梅湯', '羅漢果'].forEach((t, i) => { const x = 46 + i * (w - 92) / 5; g.fillStyle = '#f6efd2'; g.fillRect(x - 17, 190, 34, 62); vtxt(g, t, x, 192, 13.5, '#7a1d18'); });
    },
    // 源記腸粉 (華貴路): white-tiled street shop, the pull-drawer steam cabinet in an open kitchen window, red menu strips
    yuanji(g, w, h) {
      tiles(g, 0, 0, w, h, 16, '#f4f4ee', '#e9ebe4');
      g.fillStyle = '#fffdf4'; g.fillRect(0, 0, w, 62); g.strokeStyle = '#c0261c'; g.lineWidth = 5; g.strokeRect(4, 4, w - 8, 54);
      txt(g, '源記腸粉', w / 2 - 60, 33, 44, '#c0261c'); txt(g, '華貴路老舖', w / 2 + 120, 26, 16, '#c0261c', SANS, 'center', 700); txt(g, '腸粉泰斗', w / 2 + 120, 46, 15, '#1f1f1f', SERIF);
      g.fillStyle = '#20262b'; g.fillRect(24, 78, w * 0.46, 120); g.fillStyle = '#c9d2d6'; g.fillRect(40, 96, w * 0.46 - 32, 96);          // steam cabinet
      for (let j = 0; j < 4; j++) { g.fillStyle = '#9aa7ad'; g.fillRect(46, 102 + j * 23, w * 0.46 - 44, 19); g.fillStyle = '#5c676d'; g.fillRect(40 + (w * 0.46 - 32) / 2 - 16, 109 + j * 23, 32, 4); }
      for (let i = 0; i < 9; i++) { g.fillStyle = `rgba(255,255,255,${0.12 + (i % 3) * 0.08})`; g.beginPath(); g.arc(60 + i * (w * 0.46 - 60) / 8, 84 - (i % 2) * 6, 13, 0, 7); g.fill(); }
      g.fillStyle = '#b8c0c4'; g.fillRect(24, 198, w * 0.46, 58);
      const mx = w * 0.56; ['鮮蝦腸', '牛肉腸', '豬肝腸', '叉燒腸', '艇仔粥', '牛肉粥'].forEach((t, i) => { const x = mx + i * (w - mx - 24) / 5; g.fillStyle = '#c0261c'; g.fillRect(x - 14, 82, 28, 84); vtxt(g, t, x, 86, 16, '#fff8e0'); });
      g.fillStyle = '#5a3a22'; for (let i = 0; i < 3; i++) { const x = mx + 20 + i * (w - mx - 60) / 2; g.fillRect(x - 22, 196, 44, 6); g.fillRect(x - 3, 202, 6, 54); g.fillRect(x - 16, 224, 12, 32); g.fillRect(x + 6, 224, 12, 32); }
    },
    // 明記腸粉 (龍津西路, since 1981): yellow light-box sign, tables and stools seen through the open front, the boat-congee board
    mingji(g, w, h) {
      g.fillStyle = '#e8dcc0'; g.fillRect(0, 0, w, h);
      g.fillStyle = '#f5c518'; g.fillRect(0, 0, w, 62); g.fillStyle = '#b3201a'; g.fillRect(0, 58, w, 6);
      txt(g, '西關明記腸粉', w / 2, 32, 42, '#b3201a'); txt(g, '1981', 46, 34, 18, '#b3201a', SANS); txt(g, '荔枝灣', w - 56, 34, 17, '#b3201a', SERIF);
      g.fillStyle = '#3a2c22'; g.fillRect(18, 76, w - 36, 180); g.fillStyle = 'rgba(255,214,150,.35)'; g.fillRect(18, 76, w - 36, 180);
      for (let i = 0; i < Math.floor((w - 60) / 120); i++) { const x = 80 + i * 120; g.fillStyle = '#f3ead6'; g.beginPath(); g.ellipse(x, 196, 42, 12, 0, 0, 7); g.fill(); g.fillStyle = '#8a5a34'; g.fillRect(x - 4, 200, 8, 50); g.fillStyle = '#c0392b'; [-34, 34].forEach(d => { g.beginPath(); g.ellipse(x + d, 226, 12, 5, 0, 0, 7); g.fill(); g.fillRect(x + d - 2, 228, 4, 26); }); g.fillStyle = '#fff'; g.beginPath(); g.ellipse(x, 192, 20, 5, 0, 0, 7); g.fill(); }
      g.fillStyle = '#1e3326'; g.fillRect(30, 84, w - 60, 46); ['牛腩腸粉', '艇仔粥', '乾炒牛河', '鹹蛋黃蝦仁腸', '雙皮奶'].forEach((t, i) => txt(g, t, 30 + (i + 0.5) * (w - 60) / 5, 108, 19, '#f6e7a8'));
      for (let i = 0; i < 5; i++) { g.strokeStyle = '#d8c79a'; g.lineWidth = 2; g.beginPath(); g.moveTo(60 + i * (w - 120) / 4, 76); g.lineTo(60 + i * (w - 120) / 4, 84); g.stroke(); }
    },
    // 南信牛奶甜品專家 (第十甫路): red board with gold characters, white tiles, bowls of double-skin milk in a glass case
    nanxin(g, w, h) {
      tiles(g, 0, 0, w, h, 20, '#fbfbf6', '#eef3f1');
      g.fillStyle = '#a3171a'; g.fillRect(0, 0, w, 62); g.strokeStyle = '#e8c15a'; g.lineWidth = 3; g.strokeRect(6, 6, w - 12, 50);
      txt(g, '南信牛奶甜品專家', w / 2, 32, 38, '#f1cf6b');
      g.fillStyle = 'rgba(190,225,235,.55)'; g.fillRect(24, 132, w * 0.5, 70); g.strokeStyle = '#8fa3aa'; g.lineWidth = 3; g.strokeRect(24, 132, w * 0.5, 70);
      for (let i = 0; i < 7; i++) { const x = 52 + i * (w * 0.5 - 56) / 6; g.fillStyle = '#fff'; g.beginPath(); g.ellipse(x, 184, 17, 9, 0, 0, 7); g.fill(); g.fillStyle = '#fff6d8'; g.beginPath(); g.ellipse(x, 181, 13, 5, 0, 0, 7); g.fill(); g.fillStyle = '#c0392b'; g.beginPath(); g.arc(x, 180, 2.5, 0, 7); g.fill(); }
      g.fillStyle = '#a3171a'; g.fillRect(24, 202, w * 0.5, 54);
      ['雙皮奶', '薑撞奶', '鳳凰奶糊', '牛三星'].forEach((t, i) => { const x = w * 0.6 + i * (w * 0.4 - 30) / 3; g.fillStyle = '#fff'; g.strokeStyle = '#a3171a'; g.lineWidth = 3; g.fillRect(x - 17, 80, 34, 96); g.strokeRect(x - 17, 80, 34, 96); vtxt(g, t, x, 84, 19, '#a3171a'); });
      g.fillStyle = '#2b2b2b'; g.fillRect(w * 0.56, 190, w * 0.44 - 20, 66); g.fillStyle = 'rgba(255,220,160,.4)'; g.fillRect(w * 0.56, 190, w * 0.44 - 20, 66);
    },
    // 陳添記 (十五甫三巷): a back-lane shop — hand-painted red board, green timber shutters, plates of fish skin on a steel counter
    chentianji(g, w, h) {
      g.fillStyle = '#cfc9b8'; g.fillRect(0, 0, w, h); for (let i = 0; i < 400; i++) { g.fillStyle = `rgba(90,80,60,${Math.random() * 0.08})`; g.fillRect(Math.random() * w, Math.random() * h, 3, 2); }
      g.fillStyle = '#f7f1dc'; g.fillRect(14, 4, w - 28, 56); txt(g, '陳添記', w / 2 - 110, 33, 46, '#b3201a'); txt(g, '祖傳爽魚皮', w / 2 + 90, 24, 22, '#b3201a'); txt(g, '西關老字號', w / 2 + 90, 48, 15, '#1f1f1f', SANS, 'center', 700);
      g.fillStyle = '#2f6b4f'; [[18, 70], [w - 18 - 70, 70]].forEach(([x, ww]) => { g.fillRect(x, 74, ww, 182); g.fillStyle = '#245640'; for (let j = 0; j < 12; j++) g.fillRect(x + 6, 82 + j * 14, ww - 12, 4); g.fillStyle = '#2f6b4f'; });
      g.fillStyle = '#26221e'; g.fillRect(96, 74, w - 192, 182);
      g.fillStyle = '#c4ccd0'; g.fillRect(96, 168, w - 192, 88); g.fillStyle = '#e6ebee'; g.fillRect(96, 168, w - 192, 8);
      for (let i = 0; i < Math.floor((w - 230) / 58); i++) { const x = 130 + i * 58; g.fillStyle = '#fff'; g.beginPath(); g.ellipse(x, 164, 24, 8, 0, 0, 7); g.fill(); g.fillStyle = '#d8d2bd'; for (let k = 0; k < 6; k++) g.fillRect(x - 16 + k * 5, 154 + (k % 2) * 3, 4, 8); g.fillStyle = '#4c9a4a'; g.fillRect(x - 6, 152, 12, 3); }
      ['魚皮', '艇仔粥', '豬腸粉'].forEach((t, i) => { g.fillStyle = '#f7f1dc'; g.fillRect(110 + i * 46, 84, 34, 70); vtxt(g, t, 127 + i * 46, 88, 18, '#b3201a'); });
    },
    // 皇上皇臘味 (下九路, 1940): red-and-gold board, rows of cured sausages hanging over glass counters
    hsh(g, w, h) {
      g.fillStyle = '#f3e7c6'; g.fillRect(0, 0, w, h);
      g.fillStyle = '#c11a1f'; g.fillRect(0, 0, w, 66); g.fillStyle = '#f3c63c'; g.fillRect(0, 62, w, 5);
      const cx = w / 2 - 150; g.fillStyle = '#f3c63c'; g.beginPath(); g.moveTo(cx - 22, 46); g.lineTo(cx - 22, 22); g.lineTo(cx - 10, 34); g.lineTo(cx, 16); g.lineTo(cx + 10, 34); g.lineTo(cx + 22, 22); g.lineTo(cx + 22, 46); g.fill();
      txt(g, '皇上皇', w / 2 - 40, 34, 48, '#f6d24a'); txt(g, '臘味', w / 2 + 90, 34, 36, '#fff3c4'); txt(g, '始創一九四〇', w - 80, 36, 14, '#fff3c4', SANS, 'center', 700);
      g.fillStyle = '#5a3a22'; g.fillRect(16, 82, w - 32, 6);
      for (let i = 0; i < Math.floor((w - 40) / 13); i++) { const x = 22 + i * 13, L = 70 + (i % 5) * 7; g.strokeStyle = '#d9c9a0'; g.lineWidth = 1; g.beginPath(); g.moveTo(x, 88); g.lineTo(x, 96); g.stroke(); g.fillStyle = i % 4 === 0 ? '#5a1f1a' : i % 3 === 0 ? '#8e2a22' : '#a8382a'; g.fillRect(x - 3.5, 96, 7, L); g.fillStyle = 'rgba(255,230,200,.25)'; g.fillRect(x - 3.5, 96, 2, L); }
      g.fillStyle = 'rgba(190,225,235,.5)'; g.fillRect(16, 188, w - 32, 34); g.fillStyle = '#c11a1f'; g.fillRect(16, 222, w - 32, 34); txt(g, '臘腸　臘肉　臘鴨　秋風起　食臘味', w / 2, 240, 18, '#f6d24a');
    },
    // 吳系茶餐廳: Hong Kong style café — the red-white-blue of the woven carrier bag, a folding iron gate, booth seats, the menu wall
    wuxi(g, w, h) {
      const cols = ['#c8202a', '#ffffff', '#1f4fa3', '#ffffff']; for (let i = 0; i * 14 < w; i++) { g.fillStyle = cols[i % 4]; g.fillRect(i * 14, 0, 14, h); }
      g.fillStyle = '#c8202a'; g.fillRect(0, 0, w, 62); g.fillStyle = '#1f4fa3'; g.fillRect(0, 58, w, 6); txt(g, '吳系茶餐廳', w / 2, 32, 40, '#ffffff', SERIF, 'center', 900, w - 60);
      g.fillStyle = '#20262b'; g.fillRect(w * 0.08, 74, w * 0.84, h - 74); g.fillStyle = 'rgba(255,214,150,.38)'; g.fillRect(w * 0.08, 74, w * 0.84, h - 74);
      for (let i = 0; i < 3; i++) { const x = w * 0.16 + i * w * 0.17; g.fillStyle = '#2f6b4f'; g.fillRect(x - 30, 150, 60, 62); g.fillStyle = '#245640'; g.fillRect(x - 30, 150, 60, 8); g.fillStyle = '#e9e2cf'; g.fillRect(x - 22, 176, 44, 6); g.fillStyle = '#7a5a34'; g.fillRect(x - 3, 182, 6, 30); }
      ['菠蘿油', '絲襪奶茶', '燒鵝飯', '雲吞麵', '八寶飯'].forEach((t2, i) => { const x = w * 0.6 + i * w * 0.062; g.fillStyle = i % 2 ? '#ffffff' : '#fff3d0'; g.fillRect(x - 12, 82, 24, 92); vtxt(g, t2, x, 86, 15, i % 2 ? '#1f4fa3' : '#c8202a'); });
      g.strokeStyle = '#8f979c'; g.lineWidth = 2; for (let i = 0; i < 7; i++) { const x = w * 0.84 + i * 9; g.beginPath(); g.moveTo(x, 74); g.lineTo(x, h); g.stroke(); for (let y = 84; y < h; y += 18) { g.beginPath(); g.moveTo(x, y); g.lineTo(x + 9, y + 9); g.lineTo(x, y + 18); g.stroke(); } }
      g.fillStyle = '#c8202a'; g.fillRect(w * 0.08, h - 30, w * 0.74, 30); txt(g, '港式燒味　即叫即做', w * 0.45, h - 14, 16, '#fff', SANS, 'center', 700, w * 0.7);
    },
    // 廣州酒家 (文昌南路, 1935): dark-red board with gold characters, "食在廣州第一家", a round moon-gate entrance, manchu windows
    gzjj(g, w, h) {
      g.fillStyle = '#efe4c6'; g.fillRect(0, 0, w, h);
      g.fillStyle = '#7a1512'; g.fillRect(0, 0, w, 66); g.strokeStyle = '#f3d98a'; g.lineWidth = 3; g.strokeRect(6, 6, w - 12, 54); txt(g, '廣州酒家', w / 2, 34, 46, '#f3d98a', SERIF, 'center', 900, w - 80);
      const cx = w / 2; g.fillStyle = '#7a1512'; g.fillRect(cx - 86, 84, 172, h - 84); g.fillStyle = '#231c16'; g.beginPath(); g.arc(cx, 176, 70, 0, 7); g.fill(); g.fillRect(cx - 44, 176, 88, h - 176);
      g.strokeStyle = '#f3d98a'; g.lineWidth = 5; g.beginPath(); g.arc(cx, 176, 72, 0, 7); g.stroke(); g.fillStyle = 'rgba(255,205,130,.4)'; g.beginPath(); g.arc(cx, 176, 62, 0, 7); g.fill();
      [w * 0.14, w * 0.86].forEach(x => { g.fillStyle = '#f8f2e3'; g.fillRect(x - 54, 88, 108, 122); manchu(g, x - 48, 94, 96, 110, 4, 5); });
      [[cx - 112, '食在廣州'], [cx + 112, '第一家']].forEach(([x, t2]) => { g.fillStyle = '#141210'; g.fillRect(x - 15, 84, 30, t2.length * 24 + 10); vtxt(g, t2, x, 88, 21, '#f3d98a'); });
      g.fillStyle = '#7a1512'; g.fillRect(0, h - 26, w, 26); txt(g, '文昌雞　蝦餃　月餅　始創一九三五', w / 2, h - 12, 15, '#f3d98a', SANS, 'center', 700, w - 30);
    },
  };
  T.shopFace = (key, wm, hm = 2.6) => { const t = ctex(Math.round(wm * PXM), Math.round(hm * PXM), (g, w, h) => { g.save(); g.scale(1, h / 256); SHOPFACE[key](g, w, 256); g.restore(); }); t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping; return t; };
  // the two tea houses behind the spawns: 陶陶居 (black-lacquer board, gold characters) and 蓮香樓
  T.teaFace = (name, wm, hm, o) => { const t = ctex(Math.round(wm * 28), Math.round(hm * 28), (g, w, h) => {
    const P = 28, Y = m => h - m * P; g.fillStyle = o.wall; g.fillRect(0, 0, w, h); speckle(g, w, h, 5000, 0.05);
    const bays = Math.round(wm / 4.5), bw = w / bays;
    for (let b = 0; b < bays; b++) {
      g.fillStyle = o.trim; g.fillRect(b * bw, Y(hm), 9, h); g.fillRect((b + 1) * bw - 9, Y(hm), 9, h);
      for (let fl = 1; fl < Math.floor(hm / 3.6); fl++) { const y0 = fl * 3.6 + 0.9; g.fillStyle = o.trim; g.fillRect(b * bw + 14, Y(y0 + 2.2) - 4, bw - 28, 2.2 * P + 8); manchu(g, b * bw + 18, Y(y0 + 2.2), bw - 36, 2.2 * P, 6, 4); g.fillStyle = o.rail; g.fillRect(b * bw + 9, Y(y0 - 0.1), bw - 18, 0.75 * P); for (let k = 0; k < 9; k++) { g.fillStyle = o.trim; g.fillRect(b * bw + 16 + k * (bw - 32) / 8, Y(y0 - 0.15), 3, 0.6 * P); } }
      g.fillStyle = '#241c16'; g.fillRect(b * bw + 14, Y(3.2), bw - 28, 3.2 * P); g.fillStyle = 'rgba(255,205,130,.42)'; g.fillRect(b * bw + 20, Y(3.0), bw - 40, 2.6 * P);
      g.fillStyle = o.col; g.fillRect(b * bw + 9, Y(3.5), 7, 3.5 * P); g.fillRect((b + 1) * bw - 16, Y(3.5), 7, 3.5 * P);
    }
    for (let fl = 1; fl <= Math.floor(hm / 3.6); fl++) { g.fillStyle = o.trim; g.fillRect(0, Y(fl * 3.6 + 0.1), w, 7); }
    const bwid = Math.min(w * 0.72, name.length * 96 + 70); g.fillStyle = o.board; g.fillRect(w / 2 - bwid / 2, Y(4.7), bwid, 1.3 * P + 22); g.strokeStyle = o.gold; g.lineWidth = 4; g.strokeRect(w / 2 - bwid / 2 + 5, Y(4.7) + 5, bwid - 10, 1.3 * P + 12);
    txt(g, name.split('').join(' '), w / 2, Y(4.7) + 31, 46, o.gold, SERIF, 'center', 900, bwid - 34);
    if (o.side) { [0.08, 0.92].forEach((u, i) => { g.fillStyle = o.board; g.fillRect(w * u - 16, Y(hm - 0.6), 32, o.side[i].length * 30 + 12); vtxt(g, o.side[i], w * u, Y(hm - 0.6) + 6, 25, o.gold); }); }
  }); t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping; return t; };
  // weathered granite boulders for the Five Rams mound
  T.rock = ctex(512, 512, (g, w, h) => {
    g.fillStyle = '#aaa59a'; g.fillRect(0, 0, w, h);
    for (let i = 0; i < 46; i++) { const x = rnd() * w, y = rnd() * h, r = rr(40, 110); const gr = g.createRadialGradient(x - r * 0.3, y - r * 0.3, 4, x, y, r); gr.addColorStop(0, shade('#c9c3b7', rr(-0.03, 0.04))); gr.addColorStop(1, shade('#a39d92', rr(-0.04, 0.03))); g.fillStyle = gr; g.beginPath(); const n = 9; for (let k = 0; k <= n; k++) { const a = k / n * 6.283, q = r * rr(0.75, 1.05); g[k ? 'lineTo' : 'moveTo'](x + Math.cos(a) * q, y + Math.sin(a) * q); } g.fill(); g.strokeStyle = 'rgba(70,64,56,.28)'; g.lineWidth = 2; g.stroke(); }
    speckle(g, w, h, 7000, 0.1);
  });
  return { seed: v => { if (v !== undefined) seed = v; return seed; }, T, rnd, rr, shade, MANCHU, SHOPS };
})();

})()); }

// builds the draft's scene; returns a group whose y = 0 is street level
function cantonDesign() {
  const GZT = cantonGZT(), M = GZ, { T, rnd, rr } = GZT;
  if (cantonDesign.seed === undefined) cantonDesign.seed = GZT.seed(); else GZT.seed(cantonDesign.seed);     // same random scatter every time the map is built
  const G = { map: new THREE.Group(), decor: new THREE.Group(), env: new THREE.Group() }, rootG = new THREE.Group(); rootG.add(G.map, G.decor, G.env);
  let CUR = null;
  // ---------------- materials (all UVs are in metres; a material's texture repeats every su × sv metres)
  const mats = {};
  function std(name, map, su, sv, o = {}) {
    const p = Object.assign({ roughness: 0.85 }, o);
    if (map) { const t = map.clone(); t.needsUpdate = true; t.repeat.set(1 / su, 1 / (sv || su)); p.map = t; }
    const m = new THREE.MeshStandardMaterial(p); m.name = name; mats[name] = m; return m;
  }
  std('granite', T.granite, 4); std('stone', T.stone, 2.4, 2.4, { color: 0xf4f0e8 }); std('canal', T.canal, 6, 2.0);
  std('bed', T.granite, 4, 4, { color: 0x9a978c }); std('brick', T.brick, 2); std('terrace', T.terrace, 2.4);
  std('tiles', T.tiles, 2.0); std('greenTiles', T.greenTiles, 1.2); std('wood', T.wood, 1, 2); std('bamboo', T.bamboo, 1.4, 0.35);
  std('plaster', T.stone, 3, 3, { color: 0xf1e3c2 }); std('plasterW', T.stone, 3, 3, { color: 0xf6f1e6 });
  std('manchu', T.manchu, 1.2, 1.2, { emissive: 0x332211, roughness: 0.3 }); std('shopfront', T.shopfront, 8, 2.6);
  std('teahouse', T.teahouse, 36, 12.6);
  T.facade.forEach((t, i) => std('fac' + i, t, 4, 12.8));
  std('gable', T.stone, 3, 3, { color: 0x8c9296 });
  std('dark', null, 1, 1, { color: 0x2a2b30, roughness: 0.6, metalness: 0.4 });
  std('iron', null, 1, 1, { color: 0x30343a, roughness: 0.45, metalness: 0.6 });
  std('red', null, 1, 1, { color: 0xb3261e, roughness: 0.5 });
  std('gold', null, 1, 1, { color: 0xd8a640, roughness: 0.35, metalness: 0.7 });
  std('steel', null, 1, 1, { color: 0xc9ced3, roughness: 0.35, metalness: 0.15 });
  std('teal', null, 1, 1, { color: 0x2f7d6d, roughness: 0.6 });
  std('blue', null, 1, 1, { color: 0x2e5f9e, roughness: 0.55 });
  std('leaf', null, 1, 1, { color: 0x3f6f38, roughness: 0.9, flatShading: true });
  std('leafL', null, 1, 1, { color: 0x6c9a45, roughness: 0.9, flatShading: true });
  std('bark', null, 1, 1, { color: 0x857565, roughness: 0.95 });
  std('flower', null, 1, 1, { color: 0xe4402a, roughness: 0.6, emissive: 0x3a0800 });
  std('lantern', null, 1, 1, { color: 0xc8291c, roughness: 0.45, emissive: 0x4a0a00 });
  std('redwall', T.stone, 2.4, 2.4, { color: 0xb5503f }); std('redstone', T.canal, 4, 1.6, { color: 0xc98a78 });
  std('rock', T.rock, 5, 5); std('statue', null, 1, 1, { color: 0xd9d4c8, roughness: 0.9, flatShading: true });
  std('hull', null, 1, 1, { color: 0x4a2c1a, roughness: 0.7 }); std('sausage', null, 1, 1, { color: 0x9a2f24, roughness: 0.6 });
  std('doorRed', null, 1, 1, { color: 0x5a1a14, roughness: 0.6, side: THREE.DoubleSide }); std('woodDS', T.wood, 1, 2, { side: THREE.DoubleSide });
  std('yellow', null, 1, 1, { color: 0xf2c230, roughness: 0.6 }); std('white', null, 1, 1, { color: 0xf4f1e8, roughness: 0.7 });
  std('grass', null, 1, 1, { color: 0x6e9b4a, roughness: 1 });

  // ---------------- geometry helpers
  function boxGeo(x0, x1, y0, y1, z0, z1) {
    const w = x1 - x0, h = y1 - y0, d = z1 - z0, g = new THREE.BoxGeometry(w, h, d);
    const uv = g.attributes.uv, dims = [[d, h], [d, h], [w, d], [w, d], [w, h], [w, h]];
    for (let f = 0; f < 6; f++) for (let k = 0; k < 4; k++) { const i = f * 4 + k; uv.setXY(i, uv.getX(i) * dims[f][0], uv.getY(i) * dims[f][1]); }
    g.translate((x0 + x1) / 2, (y0 + y1) / 2, (z0 + z1) / 2); return g;
  }
  // m: one material or [side, top] or a 6-array (+x,-x,+y,-y,+z,-z)
  function box(group, x0, x1, y0, y1, z0, z1, m, o = {}) {
    let mm = m; if (Array.isArray(m) && m.length === 2) mm = [m[0], m[0], m[1], m[0], m[0], m[0]];
    const mesh = new THREE.Mesh(boxGeo(x0, x1, y0, y1, z0, z1), mm);
    mesh.castShadow = o.cast !== false; mesh.receiveShadow = true; Object.assign(mesh.userData, o.ud || {});
    if (CUR && !CUR.oob && group === G.map && x0 === CUR.x0 && x1 === CUR.x1 && z0 === CUR.z0 && z1 === CUR.z1 && y1 === CUR.h && y0 === (CUR.float ? CUR.y0 : (CUR.y0 || 0))) return mesh;
    group.add(mesh); return mesh;
  }
  // a prism along an axis from a 2D profile [[u, y]...]: axis 'z' → u is world z, extruded along x from a0 to a1
  function prism(group, pts, axis, a0, a1, m, o = {}) {
    const sh = new THREE.Shape(pts.map(([u, y]) => new THREE.Vector2(axis === 'z' ? -u : u, y)));
    const g = new THREE.ExtrudeGeometry(sh, { depth: a1 - a0, bevelEnabled: false, curveSegments: 24 });
    if (axis === 'z') { g.rotateY(Math.PI / 2); g.translate(a0, 0, 0); } else { g.translate(0, 0, a0); }
    const mesh = new THREE.Mesh(g, m); mesh.castShadow = o.cast !== false; mesh.receiveShadow = true; Object.assign(mesh.userData, o.ud || {}); group.add(mesh); return mesh;
  }
  function cyl(group, x, y0, z, r0, r1, h, m, seg = 12) {
    const g = new THREE.CylinderGeometry(r1, r0, h, seg); g.translate(x, y0 + h / 2, z);
    const mesh = new THREE.Mesh(g, m); mesh.castShadow = true; mesh.receiveShadow = true; group.add(mesh); return mesh;
  }
  function between(group, a, b, r, m, seg = 6) {
    const d = new THREE.Vector3().subVectors(b, a), L = d.length();
    const g = new THREE.CylinderGeometry(r, r, L, seg); g.translate(0, L / 2, 0);
    const mesh = new THREE.Mesh(g, m); mesh.position.copy(a); mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.normalize()); mesh.castShadow = true; group.add(mesh); return mesh;
  }
  function plane(group, w, h, m, pos, rotY = 0, ds = false) {
    const g = new THREE.PlaneGeometry(w, h); const uv = g.attributes.uv; if (!m.userData.unit) for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * w, uv.getY(i) * h);
    const mesh = new THREE.Mesh(g, m); mesh.position.copy(pos); mesh.rotation.y = rotY; group.add(mesh); if (ds) { const back = new THREE.Mesh(g, m); back.position.copy(pos); back.rotation.y = rotY + Math.PI; back.castShadow = true; group.add(back); } return mesh;
  }
  const signMat = (txt, bg, fg) => { const m = new THREE.MeshStandardMaterial({ map: T.sign(txt, bg, fg), roughness: 0.6 }); m.userData.unit = true; return m; };
  const plaqueMat = (txt) => { const m = new THREE.MeshStandardMaterial({ map: T.plaque(txt), roughness: 0.5 }); m.userData.unit = true; return m; };
  const V = (x, y, z) => new THREE.Vector3(x, y, z);
  const H = s => ({ ud: { hy: s.t === 'ramp' ? Math.max(s.h0, s.h1) : s.h, solid: true } });

  const { XH, ZH, CANAL } = M;
  // ---------------- solids
  const bridgesDone = new Set();
  const stairs = (s, m) => {
    const rise = Math.abs(s.h1 - s.h0), n = Math.max(2, Math.round(rise / 0.22)), up = s.h1 > s.h0;
    for (let i = 0; i < n; i++) {
      const t0 = i / n, t1 = (i + 1) / n, y = rise * (i + 1) / n;
      if (s.axis === 'z') { const za = up ? s.z0 + (s.z1 - s.z0) * t0 : s.z0 + (s.z1 - s.z0) * (1 - t1), zb = up ? s.z1 : s.z0 + (s.z1 - s.z0) * (1 - t0); box(G.map, s.x0, s.x1, 0, y, up ? za : s.z0, up ? s.z1 : zb, [m, m], H(s)); }
      else { const xa = up ? s.x0 + (s.x1 - s.x0) * t0 : s.x0, xb = up ? s.x1 : s.x0 + (s.x1 - s.x0) * (1 - t0); box(G.map, xa, xb, 0, y, s.z0, s.z1, [m, m], H(s)); }
    }
  };
  const ramp = (s, side, top) => {
    const pts = s.axis === 'z' ? [[s.z0, 0], [s.z1, 0], [s.z1, s.h1], [s.z0, s.h0]] : [[s.x0, 0], [s.x1, 0], [s.x1, s.h1], [s.x0, s.h0]];
    prism(G.map, pts, s.axis, s.axis === 'z' ? s.x0 : s.z0, s.axis === 'z' ? s.x1 : s.z1, [top, side], H(s));
  };
  const plinth = (s, h = 0.45) => box(G.map, s.x0 - 0.04, s.x1 + 0.04, s.y0 || 0, (s.y0 || 0) + h, s.z0 - 0.04, s.z1 + 0.04, mats.stone, { ud: { hy: s.h, solid: true } });
  const shrubs = (x0, x1, z0, z1, y, n) => { for (let i = 0; i < n; i++) { const g = new THREE.IcosahedronGeometry(rr(0.35, 0.6), 0); g.scale(1, 0.75, 1); const m = new THREE.Mesh(g, rnd() < 0.5 ? mats.leaf : mats.leafL); m.position.set(rr(x0 + 0.3, x1 - 0.3), y + 0.25, rr(z0 + 0.3, z1 - 0.3)); m.castShadow = true; G.decor.add(m); } };
  function steamerStack(x, z, y0, h) { const n = Math.max(1, Math.round(h / 0.22)); for (let i = 0; i < n; i++) cyl(G.decor, x, y0 + i * 0.22, z, 0.36, 0.36, 0.2, mats.bamboo, 14); cyl(G.decor, x, y0 + n * 0.22, z, 0.37, 0.3, 0.08, mats.bamboo, 14); }
  function wokEar(x0, x1, z0, z1, y0, y1) { wokEarAx('z', z0, z1, x0, x1, y0, y1, G.map); }
  // axis 'z': the gable spans z (a0..a1) and is t0..t1 thick in x; axis 'x': spans x, thick in z
  function wokEarAx(axis, a0, a1, t0, t1, y0, y1, group) {
    const L = a1 - a0, c = (a0 + a1) / 2, shoulder = y0 + (y1 - y0) * 0.45, pts = [];
    pts.push([a0, y0], [a0 - 0.18, shoulder]);
    for (let i = 0; i <= 24; i++) { const a = Math.PI - i / 24 * Math.PI; pts.push([c + Math.cos(a) * (L / 2 + 0.18), shoulder + Math.sin(a) * (y1 - shoulder)]); }
    pts.push([a1, y0]);
    prism(group, pts, axis, t0, t1, [mats.gable, mats.plasterW], { ud: { hy: y1, solid: true } });
    const tm = (t0 + t1) / 2, curve = new THREE.CatmullRomCurve3(pts.slice(2, -1).map(([u, y]) => axis === 'z' ? V(tm, y + 0.05, u) : V(u, y + 0.05, tm)));
    const tube = new THREE.Mesh(new THREE.TubeGeometry(curve, 48, 0.14, 6), mats.dark); tube.castShadow = true; group.add(tube);
  }
  for (const s of M.solids) {
    const k = s.kind; CUR = s;
    if (k === 'bridge') {
      if (bridgesDone.has(s.x0)) continue; bridgesDone.add(s.x0);
      const yb = z => 0.9 * Math.min(1, Math.max(0, (3.5 - Math.abs(z)) / 2.3));
      [s.x0 + 0.15, s.x1 - 0.15].forEach(x => {
        for (let z = -3.2; z <= 3.21; z += 0.8) { const y = yb(z); box(G.decor, x - 0.1, x + 0.1, y, y + 0.85, z - 0.1, z + 0.1, mats.stone); }
        [[-3.5, -1.2], [-1.2, 1.2], [1.2, 3.5]].forEach(([za, zb]) => between(G.decor, V(x, yb(za) + 0.85, za), V(x, yb(zb) + 0.85, zb), 0.09, mats.stone, 6));
      });
      continue;
    }
    if (k === 'stair' || s.t === 'ramp') continue;      // slopes are drawn (and inked) by the game
    if (s.t === 'fence') {   // 趟栊: odd number of round timber bars across the doorway, with an open half-door
      const n = 13; for (let i = 0; i < n; i++) { const y = 0.15 + i * (s.h - 0.3) / (n - 1); between(G.map, V((s.x0 + s.x1) / 2, y, s.z0), V((s.x0 + s.x1) / 2, y, s.z1), 0.05, mats.wood, 8).userData = { hy: s.h, solid: true }; }
      box(G.map, s.x0, s.x1, 0, s.h, s.z0 - 0.12, s.z0, mats.wood, { ud: { hy: s.h, solid: true } }); box(G.map, s.x0, s.x1, 0, s.h, s.z1, s.z1 + 0.12, mats.wood, { ud: { hy: s.h, solid: true } });
      continue;
    }
    const y0 = s.y0 || 0;
    switch (k) {
      case 'terrace': box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.fac3, mats.terrace], H(s)); break;
      case 'tank': box(G.map, s.x0, s.x1, 2.0, 2.2, s.z0, s.z1, mats.dark, H(s)); cyl(G.map, (s.x0 + s.x1) / 2, 2.2, (s.z0 + s.z1) / 2, 0.95, 0.95, s.h - 2.2, mats.steel, 20).userData = { hy: s.h, solid: true }; break;
      case 'teahouse': box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.plaster, mats.terrace], H(s)); break;
      case 'arcade': {
        box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.plaster, mats.terrace], H(s));
        // segmental arches between the columns on the street side, cornice line
        const ax = s.team ? s.x1 : s.x0;
        for (let i = 0; i < 7; i++) {
          const c0 = 8.6 + i * 3.914 + 0, c1 = c0 + 3.314; const za = s.team ? -c1 : c0, zb = s.team ? -c0 : c1;
          const pts = [[za, y0], [zb, y0], [zb, y0 - 0.4]]; for (let j = 1; j < 16; j++) { const t = j / 16; pts.push([zb + (za - zb) * t, y0 - 0.4 + 0.32 * Math.sin(t * Math.PI)]); } pts.push([za, y0 - 0.4]);
          prism(G.map, pts, 'z', ax - 0.15, ax + 0.15, mats.plasterW, { ud: { hy: 3, solid: true } });
        }
        box(G.map, ax - 0.2, ax + 0.2, s.h - 0.05, s.h + 0.05, s.z0, s.z1, mats.plasterW);
        break;
      }
      case 'balustrade': {
        const x = (s.x0 + s.x1) / 2;
        box(G.map, s.x0, s.x1, s.h - 0.12, s.h, s.z0, s.z1, mats.plasterW, H(s)); box(G.map, s.x0, s.x1, y0, y0 + 0.12, s.z0, s.z1, mats.plasterW, H(s));
        const vg = new THREE.LatheGeometry([[0.05, 0], [0.09, 0.1], [0.06, 0.25], [0.1, 0.45], [0.06, 0.62], [0.07, 0.66]].map(([r, y]) => new THREE.Vector2(r, y)), 8);
        const n = Math.floor((s.z1 - s.z0) / 0.3), im = new THREE.InstancedMesh(vg, mats.plasterW, n), o = new THREE.Object3D();
        for (let i = 0; i < n; i++) { o.position.set(x, y0 + 0.12, s.z0 + 0.15 + i * 0.3); o.updateMatrix(); im.setMatrixAt(i, o.matrix); }
        im.castShadow = true; im.userData = { hy: s.h, solid: true }; G.map.add(im);
        break;
      }
      case 'column': {
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, mats.plasterW, H(s));
        box(G.map, s.x0 - 0.08, s.x1 + 0.08, 0, 0.35, s.z0 - 0.08, s.z1 + 0.08, mats.stone, H(s));
        box(G.map, s.x0 - 0.1, s.x1 + 0.1, s.h - 0.3, s.h - 0.15, s.z0 - 0.1, s.z1 + 0.1, mats.plasterW, H(s));
        break;
      }
      case 'brick': box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.brick, mats.terrace], H(s)); plinth(s, Math.min(0.5, s.h * 0.4)); break;
      case 'hall': {   // 正廳: blue brick, pitched grey-tile roof between two wok-ear gables (the rest is dressed below)
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, mats.brick, H(s)); plinth(s);
        prism(G.map, [[s.x0 - 0.4, s.h], [s.x1 + 0.4, s.h], [(s.x0 + s.x1) / 2, s.h + 1.9]], 'x', s.z0 + 0.3, s.z1 - 0.3, [mats.tiles, mats.brick], H(s));
        wokEarAx('x', s.x0 - 0.35, s.x1 + 0.35, s.z0 - 0.05, s.z0 + 0.4, s.h, s.h + 2.7, G.map); wokEarAx('x', s.x0 - 0.35, s.x1 + 0.35, s.z1 - 0.4, s.z1 + 0.05, s.h, s.h + 2.7, G.map);
        break;
      }
      case 'lintel': {
        if (s.zone === 'mansion') { box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.stone, mats.terrace], H(s)); const fx = s.team ? s.x0 - 0.01 : s.x1 + 0.01; plane(G.decor, 2.6, 0.38, plaqueMat(s.team ? '小畫舫齋' : '泰華樓'), V(fx, y0 + 0.2, (s.z0 + s.z1) / 2), s.team ? -Math.PI / 2 : Math.PI / 2); break; }
        // 獵德牌坊: granite beam, the name on both faces, two tiers of glazed green roof with upturned ends
        box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, mats.stone, H(s));
        [[s.z1 + 0.01, 0], [s.z0 - 0.01, Math.PI]].forEach(([z, ry]) => plane(G.decor, 3.4, 0.95, plaqueMat('獵德'), V(0, (y0 + s.h) / 2, z), ry));
        const zc = (s.z0 + s.z1) / 2;
        prism(G.map, [[s.z0 - 0.7, s.h], [s.z1 + 0.7, s.h], [zc, s.h + 0.8]], 'z', s.x0 - 0.6, s.x1 + 0.6, mats.greenTiles, H(s));
        box(G.map, -2.3, 2.3, s.h + 0.3, s.h + 1.0, s.z0 + 0.15, s.z1 - 0.15, mats.stone, H(s));
        prism(G.map, [[s.z0 - 0.6, s.h + 1.0], [s.z1 + 0.6, s.h + 1.0], [zc, s.h + 1.75]], 'z', -2.9, 2.9, mats.greenTiles, H(s));
        [[s.x0 - 0.6, s.h + 0.85], [s.x1 + 0.6, s.h + 0.85], [-2.9, s.h + 1.8], [2.9, s.h + 1.8]].forEach(([x, y]) => { const m = new THREE.Mesh(new THREE.ConeGeometry(0.16, 0.65, 6), mats.greenTiles); m.position.set(x, y, zc); m.rotation.z = x < 0 ? 0.6 : -0.6; G.map.add(m); });
        break;
      }
      case 'post': {
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, mats.stone, H(s)); box(G.map, s.x0 - 0.15, s.x1 + 0.15, 0, 0.6, s.z0 - 0.15, s.z1 + 0.15, mats.stone, H(s));
        [s.z0 - 0.3, s.z1 + 0.3].forEach(z => { const d = new THREE.Mesh(new THREE.CylinderGeometry(0.42, 0.42, 0.22, 16), mats.stone); d.rotation.z = Math.PI / 2; d.position.set((s.x0 + s.x1) / 2, 0.85, z); d.castShadow = true; G.decor.add(d); });   // drum stones
        break;
      }
      case 'planterbox': box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.stone, mats.grass], H(s)); shrubs(s.x0, s.x1, s.z0, s.z1, s.h, 6); break;
      case 'planter': box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.stone, mats.grass], H(s)); break;
      case 'planterwall': box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.stone, mats.grass], H(s)); shrubs(s.x0, s.x1, s.z0, s.z1, s.h, 5); break;
      case 'shop': {
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [s.team ? mats.fac2 : mats.fac6, mats.terrace], H(s));
        box(G.map, s.x0 - 0.1, s.x1 + 0.1, s.h - 0.15, s.h + 0.35, s.z0 - 0.1, s.z1 + 0.1, mats.plasterW, H(s));
        break;
      }
      case 'steamer': {
        box(G.map, s.x0, s.x1, 0, 0.02, s.z0, s.z1, mats.stone, H(s));
        if (s.team && s.h > 1) { box(G.decor, s.x0 + 0.05, s.x1 - 0.05, 0, 0.45, s.z0 + 0.05, s.z1 - 0.05, [mats.red, mats.gold]); box(G.decor, s.x0 + 0.15, s.x1 - 0.15, 0.45, 0.85, s.z0 + 0.15, s.z1 - 0.15, [mats.red, mats.gold]); box(G.decor, s.x0 + 0.3, s.x1 - 0.3, 0.85, s.h, s.z0 + 0.3, s.z1 - 0.3, [mats.red, mats.gold]); }   // stacked mooncake gift boxes
        else for (let x = s.x0 + 0.4; x < s.x1; x += 0.78) for (let z = s.z0 + 0.4; z < s.z1; z += 0.78) steamerStack(x, z, 0, s.h - 0.08);
        const m = new THREE.Mesh(boxGeo(s.x0, s.x1, 0, s.h, s.z0, s.z1), mats.bamboo); m.visible = false; m.userData = { hy: s.h, solid: true, proxy: true }; G.map.add(m);
        break;
      }
      case 'stall': {
        const zc = (s.z0 + s.z1) / 2;
        if (!s.team) {   // 牛雜檔: steel cart, a big simmering pot, skewers, red-and-white canopy
          box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.steel, mats.steel], H(s));
          cyl(G.decor, s.x0 + 0.8, s.h, zc, 0.45, 0.45, 0.35, mats.dark, 16); cyl(G.decor, s.x0 + 0.8, s.h + 0.3, zc, 0.4, 0.4, 0.06, mats.sausage, 16);
          for (let i = 0; i < 9; i++) between(G.decor, V(s.x0 + 1.7 + i * 0.12, s.h, zc - 0.2), V(s.x0 + 1.75 + i * 0.12, s.h + 0.42, zc + 0.15), 0.012, mats.bamboo, 4);
          [[s.x0, s.z0], [s.x1, s.z0], [s.x0, s.z1], [s.x1, s.z1]].forEach(([x, z]) => cyl(G.decor, x, 0, z, 0.04, 0.04, 2.4, mats.iron, 6));
          for (let i = 0; i < 6; i++) box(G.decor, s.x0 - 0.3 + i * 0.6, s.x0 + 0.3 + i * 0.6, 2.4, 2.48, s.z0 - 0.4, s.z1 + 0.4, i % 2 ? mats.white : mats.red);
          plane(G.decor, 0.6, 1.9, signMat('蘿蔔牛雜', '#7a1d18', '#ffe39a'), V(s.x1 + 0.35, 1.6, zc), Math.PI / 2, true);
        } else {         // 雞公欖: the olive seller's counter with the paper rooster and a pole of streamers
          box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.teal, mats.wood], H(s));
          for (let i = 0; i < 4; i++) { cyl(G.decor, s.x0 + 0.5 + i * 0.45, s.h, zc, 0.14, 0.14, 0.3, mats.leafL, 10); cyl(G.decor, s.x0 + 0.5 + i * 0.45, s.h + 0.3, zc, 0.15, 0.15, 0.04, mats.red, 10); }
          const rx = s.x1 - 0.6, ry = s.h, bm = new THREE.MeshStandardMaterial({ color: 0xe0562c, roughness: 0.7, flatShading: true });
          const body = new THREE.Mesh(new THREE.SphereGeometry(0.42, 10, 8), bm); body.scale.set(1.3, 0.95, 0.85); body.position.set(rx, ry + 0.55, zc); body.castShadow = true; G.decor.add(body);
          const head = new THREE.Mesh(new THREE.SphereGeometry(0.18, 8, 6), mats.yellow); head.position.set(rx - 0.55, ry + 1.05, zc); G.decor.add(head); between(G.decor, V(rx - 0.4, ry + 0.7, zc), V(rx - 0.55, ry + 1.0, zc), 0.1, mats.yellow, 6);
          const comb = new THREE.Mesh(new THREE.ConeGeometry(0.1, 0.22, 4), mats.red); comb.position.set(rx - 0.55, ry + 1.3, zc); G.decor.add(comb); const beak = new THREE.Mesh(new THREE.ConeGeometry(0.05, 0.16, 4), mats.gold); beak.rotation.z = Math.PI / 2; beak.position.set(rx - 0.78, ry + 1.05, zc); G.decor.add(beak);
          [mats.blue, mats.leafL, mats.red, mats.yellow, mats.dark].forEach((m, i) => { const f = new THREE.Mesh(new THREE.ConeGeometry(0.07, 0.75, 4), m); f.position.set(rx + 0.6, ry + 0.85 + i * 0.04, zc - 0.2 + i * 0.1); f.rotation.z = -0.9 + i * 0.12; G.decor.add(f); });
          between(G.decor, V(s.x0 + 0.1, 0, s.z1), V(s.x0 + 0.1, 2.9, s.z1), 0.03, mats.bamboo); [mats.red, mats.yellow, mats.leafL, mats.blue].forEach((m, i) => box(G.decor, s.x0 + 0.12, s.x0 + 0.16, 2.1 + i * 0.18, 2.24 + i * 0.18, s.z1 + 0.02, s.z1 + 0.5, m));
          plane(G.decor, 0.6, 1.5, signMat('雞公欖', '#1e3326', '#ffe39a'), V(s.x0 - 0.35, 1.5, zc), Math.PI / 2, true);
        }
        break;
      }
      case 'trike': {
        box(G.map, s.x0 + 0.1, s.x1 - 0.1, 0.5, s.h, s.z0, s.z0 + 1.6, [s.team ? mats.red : mats.blue, mats.wood], H(s));
        box(G.map, s.x0 + 0.1, s.x1 - 0.1, 0, 0.5, s.z0 + 0.2, s.z0 + 1.4, mats.dark, H(s));
        const wg = new THREE.TorusGeometry(0.32, 0.07, 8, 16);
        [[s.x0 + 0.05, s.z0 + 0.8], [s.x1 - 0.05, s.z0 + 0.8], [(s.x0 + s.x1) / 2, s.z1 - 0.3]].forEach(([x, z]) => { const w = new THREE.Mesh(wg, mats.dark); w.position.set(x, 0.38, z); w.rotation.y = Math.PI / 2; G.decor.add(w); });
        between(G.decor, V((s.x0 + s.x1) / 2, 0.4, s.z1 - 0.3), V((s.x0 + s.x1) / 2, 1.0, s.z0 + 1.7), 0.04, mats.iron);
        const hb = new THREE.Mesh(boxGeo(s.x0 + 0.4, s.x1 - 0.4, 1.0, 1.06, s.z0 + 1.68, s.z0 + 1.74), mats.iron); G.decor.add(hb);
        const m = new THREE.Mesh(boxGeo(s.x0, s.x1, 0, s.h, s.z0, s.z1), mats.dark); m.visible = false; m.userData = { hy: s.h, solid: true, proxy: true }; G.map.add(m);
        if (!s.team) steamerStack((s.x0 + s.x1) / 2, s.z0 + 0.8, s.h, 0.5);
        else for (let i = 0; i < 14; i++) { const f = new THREE.Mesh(new THREE.IcosahedronGeometry(rr(0.14, 0.22), 0), [mats.flower, mats.yellow, mats.white, mats.leafL][i % 4]); f.position.set(rr(s.x0 + 0.3, s.x1 - 0.3), s.h + rr(0.1, 0.4), rr(s.z0 + 0.2, s.z0 + 1.4)); G.decor.add(f); }   // flower-market trike
        break;
      }
      case 'landing': box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, mats.stone, H(s)); break;
      case 'deck': {
        box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.stone, mats.granite], H(s));
        [s.x0, s.x1].forEach(x => { for (let i = 0; i < 3; i++) { const z0 = -3.5 + i * 7 / 3 + 0.25, z1 = z0 + 7 / 3 - 0.5; prism(G.map, [[z0, y0], [z1, y0], [z1, y0 - 0.25], [(z0 + z1) / 2, y0 - 0.05], [z0, y0 - 0.25]], 'z', x - 0.12, x + 0.12, mats.stone); } });
        break;
      }
      case 'hall2': {   // the ancestral hall: blue-brick walls, granite base, red doors, a flat roof terrace with a glazed ridge parapet
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.brick, mats.terrace], H(s)); plinth(s, 0.9);
        box(G.map, s.x0 - 0.12, s.x1 + 0.12, s.h - 0.35, s.h - 0.1, s.z0 - 0.12, s.z1 + 0.12, mats.plasterW, H(s));
        [[s.z1 + 0.03, 0], [s.z0 - 0.03, Math.PI]].forEach(([z, ry], i) => {
          plane(G.map, 1.8, 2.6, mats.red, V(0, 1.3 + 0.9 - 0.9, z), ry).position.y = 1.3 + 0.0;
          plane(G.map, 2.2, 0.55, plaqueMat(i ? '浪氏书院' : '墨浪祠'), V(0, 3.15, z + (i ? -0.01 : 0.01)), ry);
          // a green-tiled eave over the door
          const zz = i ? s.z0 : s.z1, sg = i ? -1 : 1;
          prism(G.map, [[zz, 3.45], [zz + sg * 0.9, 3.05], [zz + sg * 0.9, 2.95], [zz, 3.3]].map(([z, y]) => [z, y]), 'z', -1.6, 1.6, mats.greenTiles);
          [-1.25, 1.25].forEach(x => box(G.map, x - 0.16, x + 0.16, 0, 3.05, zz + sg * 0.62 - 0.16, zz + sg * 0.62 + 0.16, mats.stone));
          box(G.map, s.x0, s.x1, s.h, s.h + 0.12, i ? s.z0 : s.z1 - 0.24, i ? s.z0 + 0.24 : s.z1, mats.greenTiles, H(s));
        });
        break;
      }
      case 'gable': wokEar(s.x0, s.x1, s.z0, s.z1, s.y0, s.h); break;
      case 'ridge': {   // glazed ridge across the roof terrace: green-tile base, a crest of coloured ceramic figures, curled fish at both ends
        box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.greenTiles, mats.greenTiles], H(s));
        box(G.map, s.x0, s.x1, y0, y0 + 0.18, s.z0 - 0.06, s.z1 + 0.06, mats.plasterW, H(s));
        const cols = [mats.flower, mats.gold, mats.blue, mats.greenTiles, mats.plasterW];
        for (let j = 0; j < 14; j++) { const x = s.x0 + 0.25 + j * (s.x1 - s.x0 - 0.5) / 13; const g = new THREE.CylinderGeometry(0.07, 0.1, rr(0.28, 0.45), 6); g.translate(0, 0.18, 0); const m = new THREE.Mesh(g, cols[j % 5]); m.position.set(x, s.h, 0); m.castShadow = true; G.map.add(m); const hd = new THREE.Mesh(new THREE.SphereGeometry(0.08, 8, 6), cols[(j + 2) % 5]); hd.position.set(x, s.h + 0.42, 0); G.map.add(hd); }
        [s.x0 + 0.1, s.x1 - 0.1].forEach((x, i) => { const t = new THREE.Mesh(new THREE.TorusGeometry(0.32, 0.09, 8, 16, Math.PI * 1.4), mats.blue); t.position.set(x, s.h + 0.35, 0); t.rotation.set(0, Math.PI / 2, i ? 0.3 : Math.PI - 0.3); G.map.add(t); });
        break;
      }
      case 'zhl': {   // 鎮海樓 (the "five-storey tower"): red walls, a green glazed eave round every storey; the 4 m terrace is the high point
        box(G.map, s.x0, s.x1, 0, s.h, s.z0, s.z1, [mats.redwall, mats.terrace], H(s)); box(G.map, s.x0 - 0.06, s.x1 + 0.06, 0, 0.7, s.z0 - 0.06, s.z1 + 0.06, mats.redstone, H(s));
        [1.95, 3.8].forEach(y => { box(G.decor, s.x0 - 0.38, s.x1 + 0.38, y, y + 0.1, s.z0 - 0.38, s.z1 + 0.38, mats.greenTiles); box(G.decor, s.x0 - 0.12, s.x1 + 0.12, y - 0.14, y, s.z0 - 0.12, s.z1 + 0.12, mats.plasterW); });
        [[s.z1 + 0.02, 0, 'z'], [s.z0 - 0.02, Math.PI, 'z'], [s.x1 + 0.02, Math.PI / 2, 'x'], [s.x0 - 0.02, -Math.PI / 2, 'x']].forEach(([c, ry, ax]) => {
          [-1.5, 0, 1.5].forEach(d => { const p0 = ax === 'z' ? V(d, 2.95, c) : V(c, 2.95, d); plane(G.decor, 0.7, 1.1, mats.dark, p0, ry); if (d) { const p1 = ax === 'z' ? V(d, 1.2, c) : V(c, 1.2, d); plane(G.decor, 0.7, 1.1, mats.dark, p1, ry); } });
          const pd = ax === 'z' ? V(0, 0.95, c) : V(c, 0.95, 0); plane(G.decor, 1.3, 1.9, mats.doorRed, pd, ry);
        });
        break;
      }
      case 'citywall': {   // a stretch of the old city wall the tower stands on: big stone blocks, low battlements
        box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, [mats.redstone, mats.granite], H(s));
        break;
      }
      case 'zhltop': {   // the upper storeys and the hip roof (collision is the plain 2 x 2 box)
        const m = new THREE.Mesh(boxGeo(s.x0, s.x1, y0, s.h, s.z0, s.z1), mats.rock); m.visible = false; m.userData = { hy: s.h, solid: true, proxy: true }; G.map.add(m);
        box(G.decor, -1, 1, 4.0, 5.6, -1, 1, mats.redwall); box(G.decor, -1.42, 1.42, 5.55, 5.66, -1.42, 1.42, mats.greenTiles);
        box(G.decor, -0.85, 0.85, 5.66, 7.0, -0.85, 0.85, mats.redwall); box(G.decor, -1.25, 1.25, 6.95, 7.05, -1.25, 1.25, mats.greenTiles);
        const roof = new THREE.Mesh(new THREE.ConeGeometry(1.75, 1.15, 4), mats.greenTiles); roof.rotation.y = Math.PI / 4; roof.position.set(0, 7.05 + 0.57, 0); roof.castShadow = true; G.decor.add(roof);
        box(G.decor, -0.5, 0.5, 8.1, 8.22, -0.07, 0.07, mats.greenTiles);
        [[1.01, 0], [-1.01, Math.PI]].forEach(([z, ry]) => { plane(G.decor, 1.5, 0.5, plaqueMat('鎮海樓'), V(0, 5.05, z), ry); [-0.5, 0.5].forEach(x => plane(G.decor, 0.4, 0.7, mats.dark, V(x, 4.45, z), ry)); [-0.4, 0.4].forEach(x => plane(G.decor, 0.35, 0.6, mats.dark, V(x, 6.3, z * 0.86), ry)); });
        [[1.01, Math.PI / 2], [-1.01, -Math.PI / 2]].forEach(([x, ry]) => { [-0.5, 0.5].forEach(z => plane(G.decor, 0.4, 0.7, mats.dark, V(x, 4.6, z), ry)); });
        break;
      }
      case 'boat': { const m = new THREE.Mesh(boxGeo(s.x0, s.x1, y0, s.h, s.z0, s.z1), mats.rock); m.visible = false; m.userData = { hy: s.h, solid: true, proxy: true }; G.map.add(m); break; }
      default: box(G.map, s.x0, s.x1, y0, s.h, s.z0, s.z1, mats.plaster, H(s));
    }
  }
  CUR = null;
  // canal landing-step side walls are plain granite; railings of the canal exits (outside) are iron grilles
  [-XH, XH].forEach(x => { for (let z = CANAL.z0 + 0.3; z < CANAL.z1; z += 0.35) between(G.map, V(x, CANAL.bed, z), V(x, 0.2, z), 0.04, mats.iron, 5); });

  // ================= v2 dressing: real shops and landmarks. Visual only (collision comes from the solids above).
  // Everything is written in team-0 coordinates and placed for both halves; the two halves get DIFFERENT shops.
  const W2 = (t, x, y, z) => V(t ? -x : x, y, t ? -z : z);
  const RY = (t, r) => r + (t ? Math.PI : 0);
  const bx = (t, g, x0, x1, y0, y1, z0, z1, m, o) => t ? box(g, -x1, -x0, y0, y1, -z1, -z0, m, o) : box(g, x0, x1, y0, y1, z0, z1, m, o);
  const prismT = (t, g, pts, axis, a0, a1, m) => t ? prism(g, pts.map(([u, y]) => [-u, y]).reverse(), axis, -a1, -a0, m) : prism(g, pts, axis, a0, a1, m);
  const face = (tex, w, h, pos, ry, o = {}) => { const m = new THREE.MeshStandardMaterial(Object.assign({ map: tex, roughness: 0.8 }, o)); m.userData.unit = true; const p = plane(G.decor, w, h, m, pos, ry); p.receiveShadow = true; return p; };
  const nrm = (ry, d) => V(Math.sin(ry) * d, 0, Math.cos(ry) * d);
  const manchuWin = (t, x, y, z, ry, w = 1.4, h = 1.5) => { const r = RY(t, ry), p = W2(t, x, y, z); plane(G.decor, w + 0.28, h + 0.28, mats.stone, p, r); plane(G.decor, w, h, mats.manchu, p.clone().add(nrm(r, 0.02)), r); };

  // ---- shops under the arcade: three per side, six different ones in all
  const ARC = [
    [['hzl', 8, 16, '黃振龍涼茶', '#0f5a3a', '#f6d443'], ['yuanji', 16, 26, '源記腸粉', '#fffdf4', '#c0261c'], ['nanxin', 26, 36, '南信甜品', '#a3171a', '#f1cf6b']],
    [['mingji', 8, 18, '明記腸粉', '#f5c518', '#b3201a'], ['chentianji', 18, 26, '陳添記魚皮', '#f7f1dc', '#b3201a'], ['hsh', 26, 36, '皇上皇臘味', '#c11a1f', '#f6d24a']],
  ];
  const PROP = {
    hzl: t => [10.5, 13.5].forEach(z => { const p = W2(t, 25.55, 0, z); cyl(G.decor, p.x, 0, p.z, 0.3, 0.3, 0.95, mats.teal, 10); [[0.3, 1.25], [0.19, 1.66]].forEach(([r, y]) => { const a = new THREE.Mesh(new THREE.SphereGeometry(r, 14, 10), mats.gold); a.position.set(p.x, y, p.z); a.castShadow = true; G.decor.add(a); }); cyl(G.decor, p.x, 1.8, p.z, 0.05, 0.07, 0.14, mats.gold, 8); }),
    yuanji: t => { bx(t, G.decor, 25.45, 25.95, 0, 1.15, 17.2, 18.8, mats.steel); [0, 1, 2].forEach(i => { const p = W2(t, 25.7, 1.15 + i * 0.12, 18); cyl(G.decor, p.x, p.y, p.z, 0.3, 0.3, 0.1, mats.bamboo, 12); }); },
    nanxin: t => { bx(t, G.decor, 25.5, 25.95, 0, 0.9, 27, 30, mats.red); const gm = new THREE.MeshStandardMaterial({ color: 0xcfe8ee, transparent: true, opacity: 0.35, roughness: 0.1 }); bx(t, G.decor, 25.5, 25.95, 0.9, 1.45, 27, 30, gm, { cast: false }); for (let i = 0; i < 6; i++) { const p = W2(t, 25.72, 0.92, 27.3 + i * 0.48); cyl(G.decor, p.x, p.y, p.z, 0.1, 0.15, 0.1, mats.plasterW, 10); } },
    mingji: t => [11, 15].forEach(z => { const p = W2(t, 25.3, 0, z); cyl(G.decor, p.x, 0, p.z, 0.05, 0.05, 0.72, mats.iron, 6); cyl(G.decor, p.x, 0.72, p.z, 0.45, 0.45, 0.05, mats.plasterW, 16); [-0.7, 0.7].forEach(d => { const q = W2(t, 25.3, 0, z + d); cyl(G.decor, q.x, 0, q.z, 0.16, 0.16, 0.45, mats.red, 10); }); }),
    chentianji: t => { bx(t, G.decor, 25.5, 25.95, 0, 1.0, 20.5, 23.5, mats.steel); for (let i = 0; i < 4; i++) { const p = W2(t, 25.72, 1.0, 20.9 + i * 0.7); cyl(G.decor, p.x, p.y, p.z, 0.22, 0.22, 0.04, mats.plasterW, 14); } },
    hsh: t => { between(G.decor, W2(t, 25.6, 1.72, 27), W2(t, 25.6, 1.72, 35), 0.025, mats.wood, 5); const im = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.035, 0.035, 0.55, 5), mats.sausage, 40), o = new THREE.Object3D(); for (let i = 0; i < 40; i++) { o.position.copy(W2(t, 25.6, 1.42 - (i % 3) * 0.03, 27.2 + i * 0.195)); o.updateMatrix(); im.setMatrixAt(i, o.matrix); } G.decor.add(im); },
  };
  [0, 1].forEach(t => ARC[t].forEach(([key, z0, z1, name, bg, fg]) => {
    const zc = (z0 + z1) / 2;
    face(T.shopFace(key, z1 - z0), z1 - z0, 2.6, W2(t, 25.97, 1.3, zc), RY(t, -Math.PI / 2));
    bx(t, G.decor, 25.6, 26, 0, 3.4, z1 - 0.12, z1 + 0.12, mats.plasterW); bx(t, G.decor, 25.9, 26, 2.6, 3.4, z0, z1, mats.plasterW, { cast: false });
    const sg = plane(G.decor, 0.8, Math.min(2.5, name.length * 0.5), signMat(name, bg, fg), W2(t, 19.9, 5.1, zc), 0, true); sg.castShadow = true;
    bx(t, G.decor, 20.21, 20.29, 3.8, 6.4, zc - 0.04, zc + 0.04, mats.iron);
    PROP[key](t);
  }));

  // ---- the small house in the middle street: 吳財記麵家 on one half, 順記冰室 on the other
  [['wuxi', '吳系茶餐廳', '#c8202a', '#ffffff'], ['gzjj', '廣州酒家', '#7a1512', '#f3d98a']].forEach(([key, name, bg, fg], t) => {
    face(T.shopFace(key, 7, 2.4), 7, 2.4, W2(t, -4.97, 1.2, 21.5), RY(t, Math.PI / 2));
    const m = new THREE.MeshStandardMaterial({ map: T.plaque(name, bg, fg), roughness: 0.6 }); m.userData.unit = true;
    plane(G.decor, 3.6, 0.9, m, W2(t, -5.0, 3.25, 21.5), RY(t, Math.PI / 2), true).castShadow = true;
    [20.2, 22.8].forEach(z => bx(t, G.decor, -5.06, -4.98, 2.75, 3.3, z - 0.03, z + 0.03, mats.iron));
  });

  // ---- tea houses behind the spawns: 陶陶居 (black-lacquer board, gold characters, the hexagonal 可觀亭 on the roof) and 蓮香樓
  const TEA = [
    { name: '陶陶居', o: { wall: '#e7dcc0', trim: '#f8f2e3', col: '#8e1f1a', board: '#141210', gold: '#e8c15a', rail: '#2a5a44', side: ['正宗粵菜', '星期美點'] } },
    { name: '蓮香樓', o: { wall: '#dcc9a6', trim: '#fff6e6', col: '#4a2416', board: '#7a1512', gold: '#f3d98a', rail: '#7a1512', side: ['蓮蓉月餅', '龍鳳禮餅'] } },
  ];
  TEA.forEach((c, t) => {
    face(T.teaFace(c.name, 16, 9, c.o), 16, 9, W2(t, -18, 4.5, 43.97), RY(t, Math.PI));
    face(T.teaFace(c.name, 8, 7, Object.assign({}, c.o, { side: null })), 8, 7, W2(t, -9.97, 5.5, 48), RY(t, Math.PI / 2));
    face(T.teaFace(c.name, 36, 12.6, c.o), 36, 12.6, W2(t, 8, 8.3, 51.97), RY(t, Math.PI));
    const p = W2(t, -18, 9, 48);
    if (!t) {   // 可觀亭: three tiers, six sides, green glazed tiles
      for (let i = 0; i < 3; i++) { const r = 2.7 - i * 0.65, y = p.y + i * 1.55; cyl(G.decor, p.x, y, p.z, r * 0.6, r * 0.6, 1.15, mats.plasterW, 6); for (let k = 0; k < 6; k++) { const a = k / 6 * Math.PI * 2; cyl(G.decor, p.x + Math.cos(a) * r * 0.6, y, p.z + Math.sin(a) * r * 0.6, 0.07, 0.07, 1.15, mats.red, 6); } const roof = new THREE.Mesh(new THREE.ConeGeometry(r, 0.8, 6), mats.greenTiles); roof.position.set(p.x, y + 1.15 + 0.4, p.z); roof.castShadow = true; G.decor.add(roof); }
      const tip = new THREE.Mesh(new THREE.SphereGeometry(0.24, 8, 6), mats.gold); tip.position.set(p.x, p.y + 5.05, p.z); G.decor.add(tip);
    } else {    // 蓮香樓: a curved parapet with the name over the corner
      const q = W2(t, -18, 9, 44.3); const pts = [[-4, 9], [4, 9], [4, 9.6]]; for (let j = 1; j < 12; j++) { const u = j / 12; pts.push([4 - 8 * u, 9.6 + 1.5 * Math.sin(u * Math.PI)]); } pts.push([-4, 9.6]);
      prism(G.decor, pts.map(([x, y]) => [x + q.x, y]), 'x', q.z - 0.2, q.z + 0.2, mats.plasterW);
      const m = new THREE.MeshStandardMaterial({ map: T.plaque('蓮香樓', '#7a1512', '#f3d98a'), roughness: 0.6 }); m.userData.unit = true; plane(G.decor, 4.2, 1.2, m, V(q.x, 10.0, q.z + 0.22), 0);
    }
  });

  // ---- 西關大屋, dressed after the real thing: granite footing + blue brick (solids), then
  //      腳門 / 趟櫳 / 大門 at the gate, 滿洲窗, 青雲巷 gateways, a paved 天井 with side eaves, the 正廳 with its screen doors
  [0, 1].forEach(t => {
    [18.5, 27.5].forEach(z => manchuWin(t, -14.97, 1.55, z, Math.PI / 2));                       // street wall, either side of the gate
    [[11.97, Math.PI], [34.03, 0]].forEach(([z, ry]) => {                                        // the two wing ends
      [-18, -21.3].forEach(x => manchuWin(t, x, 1.55, z, ry, 1.2, 1.4));
      const r = RY(t, ry), p = W2(t, -24.4, 1.1, z); plane(G.decor, 1.5, 2.3, mats.stone, p.clone().add(V(0, 0.05, 0)), r); plane(G.decor, 1.1, 2.1, mats.dark, p.clone().add(nrm(r, 0.02)), r);
      const m = new THREE.MeshStandardMaterial({ map: T.plaque('青雲巷', '#d7d1c4', '#3a3a3a'), roughness: 0.8 }); m.userData.unit = true; plane(G.decor, 1.2, 0.36, m, W2(t, -24.4, 2.38, z).add(nrm(r, 0.03)), r);
    });
    // gate: granite jambs, four half-height 腳門 leaves folded outward, two big 大門 leaves swung into the yard
    bx(t, G.decor, -16.06, -14.94, 0, 2.2, 20.8, 21.0, mats.stone); bx(t, G.decor, -16.06, -14.94, 0, 2.2, 25.0, 25.2, mats.stone);
    [[21.05, -1], [24.95, 1]].forEach(([z, sgn]) => {
      [0, 1].forEach(i => plane(G.decor, 0.5, 1.25, mats.woodDS, W2(t, -14.72 + i * 0.36, 1.05, z + sgn * (-0.12 - i * 0.02)), RY(t, Math.PI / 2 + sgn * (i ? 0.25 : 1.25))));
      plane(G.decor, 1.9, 2.15, mats.doorRed, W2(t, -17.0, 1.08, z - sgn * 0.18), RY(t, 0));
      [0.55, 1.5].forEach(y => bx(t, G.decor, -17.9, -16.1, y, y + 0.06, z - sgn * 0.18 - 0.03, z - sgn * 0.18 + 0.03, mats.gold));
    });
    for (let i = 0; i < 13; i++) between(G.decor, W2(t, -15.5, 0.15 + i * 0.16, 24.35), W2(t, -15.5, 0.15 + i * 0.16, 24.98), 0.045, mats.wood, 6);   // 趟櫳 pushed open
    bx(t, G.decor, -15.6, -15.4, 0, 2.2, 24.3, 24.4, mats.wood);
    // 天井: darker paving, the fish vat and potted trees on the 花台
    bx(t, G.decor, -23, -16, 0.0, 0.025, 16, 30, mats.bed, { cast: false });
    { const p = W2(t, -19.2, 1.0, 22); cyl(G.decor, p.x, p.y, p.z, 0.42, 0.5, 0.55, mats.blue, 14); cyl(G.decor, p.x, p.y + 0.5, p.z, 0.47, 0.47, 0.06, mats.white, 14);
      [23.4, 24.3].forEach(z => { const q = W2(t, -19.3, 1.0, z); cyl(G.decor, q.x, q.y, q.z, 0.16, 0.22, 0.25, mats.sausage, 10); cyl(G.decor, q.x, q.y + 0.25, q.z, 0.04, 0.05, 0.5, mats.bark, 5); [[0.2, 0.75], [-0.18, 0.9], [0.05, 1.05]].forEach(([d, y]) => { const l = new THREE.Mesh(new THREE.IcosahedronGeometry(0.2, 0), mats.leaf); l.scale.set(1.3, 0.5, 1.3); l.position.set(q.x + d, q.y + y, q.z + d * 0.5); G.decor.add(l); }); }); }
    // side eaves (廊) along both wings, on thin timber posts
    prismT(t, G.decor, [[16, 2.5], [17.15, 2.2], [17.15, 2.12], [16, 2.38]], 'z', -23, -16, mats.tiles);
    prismT(t, G.decor, [[30, 2.38], [28.85, 2.12], [28.85, 2.2], [30, 2.5]], 'z', -23, -16, mats.tiles);
    [[-22.3, 17.05], [-19.5, 17.05], [-16.7, 17.05], [-22.3, 28.95], [-19.5, 28.95], [-16.7, 28.95]].forEach(([x, z]) => { const p = W2(t, x, 0, z); cyl(G.decor, p.x, 0, p.z, 0.06, 0.06, 2.14, mats.wood, 6); });
    // 正廳 front: a row of manchu-glass screen doors, the open middle bay with the hall board, eave on two granite columns
    for (let i = 0; i < 10; i++) { const z = 16.9 + i * 1.3 + 0.2; if (z > 20.9 && z < 25.1) continue; plane(G.decor, 1.16, 2.5, mats.manchu, W2(t, -22.96, 1.3, z), RY(t, Math.PI / 2)); }
    plane(G.decor, 4.2, 2.7, mats.dark, W2(t, -22.96, 1.35, 23), RY(t, Math.PI / 2));
    { const m = new THREE.MeshStandardMaterial({ map: T.plaque('積厚流光', '#5a1512', '#e8c15a'), roughness: 0.6 }); m.userData.unit = true; plane(G.decor, 3.0, 0.75, m, W2(t, -22.93, 2.25, 23), RY(t, Math.PI / 2)); }
    plane(G.decor, 13.4, 0.5, mats.manchu, W2(t, -22.96, 3.0, 23), RY(t, Math.PI / 2));
    prismT(t, G.decor, [[-23, 3.75], [-21.85, 3.4], [-21.85, 3.32], [-23, 3.62]], 'x', 16.2, 29.8, mats.tiles);
    [20.6, 25.4].forEach(z => { const p = W2(t, -22.0, 0, z); cyl(G.decor, p.x, 0, p.z, 0.14, 0.16, 3.32, mats.stone, 10); });
  });

  // ---- 龍舟 moored in the canal: long narrow hull (the real ones are ~38 m × 1.2 m; this one is 10.5 m), dragon head and tail,
  //      drum, the ceremonial umbrella and flags. One red boat, one green boat.
  [0, 1].forEach(t => {
    const tm = t ? mats.greenTiles : mats.red, z = 0.8, y = -1.5;
    const pts = [[8.5, 0.8], [9.7, 0.26], [17.8, 0.26], [19, 0.8], [17.8, 1.34], [9.7, 1.34]].map(([x, zz]) => t ? [-x, -zz] : [x, zz]);
    const g = new THREE.ExtrudeGeometry(new THREE.Shape(pts.map(([x, zz]) => new THREE.Vector2(x, zz))), { depth: 0.6, bevelEnabled: false }); g.rotateX(Math.PI / 2); g.translate(0, y, 0);
    const hull = new THREE.Mesh(g, [mats.wood, mats.hull]); hull.castShadow = true; hull.receiveShadow = true; G.decor.add(hull);
    bx(t, G.decor, 9.6, 17.9, y - 0.12, y - 0.04, 0.22, 0.28, tm); bx(t, G.decor, 9.6, 17.9, y - 0.12, y - 0.04, 1.32, 1.38, tm);
    for (let x = 10; x < 17.8; x += 0.95) bx(t, G.decor, x, x + 0.14, y, y + 0.1, 0.34, 1.26, mats.wood);
    // head at the inner end (toward the Five Rams), tail at the outer end
    between(G.decor, W2(t, 9.1, y, z), W2(t, 8.2, y + 0.95, z), 0.17, tm, 8);
    bx(t, G.decor, 7.55, 8.4, y + 0.8, y + 1.2, z - 0.2, z + 0.2, tm); bx(t, G.decor, 7.4, 7.75, y + 0.82, y + 0.98, z - 0.16, z + 0.16, mats.gold);
    [-0.14, 0.14].forEach(d => { const h = new THREE.Mesh(new THREE.ConeGeometry(0.05, 0.42, 5), mats.gold); h.position.copy(W2(t, 8.3, y + 1.38, z + d)); h.rotation.z = t ? 0.5 : -0.5; G.decor.add(h); const ey = new THREE.Mesh(new THREE.SphereGeometry(0.06, 8, 6), mats.white); ey.position.copy(W2(t, 7.8, y + 1.1, z + d * 1.45)); G.decor.add(ey); });
    for (let i = 0; i < 5; i++) { const f = new THREE.Mesh(new THREE.ConeGeometry(0.06, 0.3, 4), mats.yellow); f.position.copy(W2(t, 8.5 + i * 0.13, y + 0.75 - i * 0.14, z)); G.decor.add(f); }
    between(G.decor, W2(t, 18.3, y, z), W2(t, 19.1, y + 0.8, z), 0.1, tm, 6);
    // drum, umbrella, flags (kept clear of the stone bridge above the outer half of the boat)
    { const p = W2(t, 12.4, y, z); cyl(G.decor, p.x, y + 0.1, p.z, 0.36, 0.36, 0.5, mats.red, 14); cyl(G.decor, p.x, y + 0.6, p.z, 0.37, 0.37, 0.03, mats.white, 14); }
    { const p = W2(t, 11.2, y, z); cyl(G.decor, p.x, y, p.z, 0.03, 0.03, 2.5, mats.bamboo, 6); const c = new THREE.Mesh(new THREE.ConeGeometry(0.75, 0.45, 12), mats.yellow); c.position.set(p.x, y + 2.5, p.z); G.decor.add(c); cyl(G.decor, p.x, y + 2.0, p.z, 0.75, 0.75, 0.28, tm, 12); }
    [9.9, 10.5, 13.2].forEach((x, i) => { const p = W2(t, x, y, z); cyl(G.decor, p.x, y, p.z, 0.02, 0.02, 1.9, mats.bamboo, 5); const f = new THREE.Mesh(new THREE.PlaneGeometry(0.7, 0.45), new THREE.MeshStandardMaterial({ color: i % 2 ? 0xf2c230 : (t ? 0x2f9b62 : 0xc8291c), side: THREE.DoubleSide })); f.position.set(p.x + (t ? -0.36 : 0.36), y + 1.65, p.z); G.decor.add(f); });
  });

  // ---------------- trees
  function kapok(x, y, z, k) {
    const h = 6.8 * k; cyl(G.decor, x, y, z, 0.32 * k, 0.16 * k, h, mats.bark, 9);
    const fl = new THREE.IcosahedronGeometry(0.17, 0); const pos = [];
    [3.2, 4.4, 5.5].forEach((hy, tier) => { for (let b = 0; b < 5; b++) { const a = b / 5 * Math.PI * 2 + tier * 0.7, L = (2.3 - tier * 0.45) * k; const p0 = V(x, y + hy * k, z), p1 = V(x + Math.cos(a) * L, y + (hy + 0.5) * k, z + Math.sin(a) * L); between(G.decor, p0, p1, 0.07 * k, mats.bark, 5); for (let f = 0; f < 6; f++) { const t = rr(0.35, 1.05); pos.push(V(p0.x + (p1.x - p0.x) * t + rr(-0.25, 0.25), p0.y + (p1.y - p0.y) * t + rr(0, 0.35), p0.z + (p1.z - p0.z) * t + rr(-0.25, 0.25))); } } });
    for (let f = 0; f < 10; f++) pos.push(V(x + rr(-0.5, 0.5), y + h + rr(-0.2, 0.3), z + rr(-0.5, 0.5)));
    const im = new THREE.InstancedMesh(fl, mats.flower, pos.length), o = new THREE.Object3D();
    pos.forEach((p, i) => { o.position.copy(p); o.rotation.set(rnd() * 3, rnd() * 3, 0); o.scale.setScalar(rr(0.8, 1.4)); o.updateMatrix(); im.setMatrixAt(i, o.matrix); }); im.castShadow = true; G.decor.add(im);
  }
  function banyan(x, y, z, k) {
    cyl(G.decor, x, y, z, 0.9, 0.55, 4.2, mats.bark, 10);
    for (let b = 0; b < 5; b++) { const a = b / 5 * Math.PI * 2; between(G.decor, V(x, y + 3.4, z), V(x + Math.cos(a) * 2.6, y + 4.8, z + Math.sin(a) * 2.6), 0.22, mats.bark, 6); }
    for (let i = 0; i < 9; i++) { const a = i / 9 * Math.PI * 2, r = i ? rr(2.0, 3.4) : 0; const g = new THREE.IcosahedronGeometry(rr(2.0, 2.8), 1); g.scale(1, 0.62, 1); const m = new THREE.Mesh(g, i % 3 ? mats.leaf : mats.leafL); m.position.set(x + Math.cos(a) * r, y + rr(5.0, 6.2), z + Math.sin(a) * r); m.castShadow = true; m.receiveShadow = true; G.decor.add(m); }
    for (let i = 0; i < 26; i++) { const a = rnd() * Math.PI * 2, r = rr(1.0, 2.3), top = y + rr(4.0, 4.6); between(G.decor, V(x + Math.cos(a) * r, y, z + Math.sin(a) * r), V(x + Math.cos(a) * r * 1.1, top, z + Math.sin(a) * r * 1.1), rr(0.025, 0.06), mats.bark, 4); }
  }
  M.trees.forEach(t => t.kind === 'kapok' ? kapok(t.x, t.y, t.z, t.k) : banyan(t.x, t.y, t.z, t.k));

  // ---------------- street dressing: lantern strings, signs on the arcade, laundry on roofs, water tank stands
  const lanternG = new THREE.SphereGeometry(0.17, 12, 8); lanternG.scale(1, 1.25, 1);
  function lanterns(a, b, sag, n) {
    const pts = []; for (let i = 0; i <= 20; i++) { const t = i / 20; pts.push(V(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t - Math.sin(t * Math.PI) * sag, a.z + (b.z - a.z) * t)); }
    const c = new THREE.CatmullRomCurve3(pts); G.decor.add(new THREE.Mesh(new THREE.TubeGeometry(c, 40, 0.015, 4), mats.iron));
    for (let i = 1; i < n; i++) { const p = c.getPoint(i / n); const m = new THREE.Mesh(lanternG, mats.lantern); m.position.set(p.x, p.y - 0.25, p.z); G.decor.add(m); }
  }
  function laundry(a, b) {
    between(G.decor, V(a.x, a.y, a.z), V(a.x, a.y + 1.9, a.z), 0.04, mats.bamboo); between(G.decor, V(b.x, b.y, b.z), V(b.x, b.y + 1.9, b.z), 0.04, mats.bamboo);
    between(G.decor, V(a.x, a.y + 1.85, a.z), V(b.x, b.y + 1.85, b.z), 0.025, mats.bamboo);
    const cols = [0xe8d9b5, 0x4a7fc1, 0xd85a4a, 0xf2f2f0, 0x6fae6a, 0xf0c64a]; const n = 5;
    for (let i = 1; i <= n; i++) { const t = i / (n + 1), w = rr(0.4, 0.75), h = rr(0.6, 1.0); const m = new THREE.Mesh(new THREE.PlaneGeometry(w, h), new THREE.MeshStandardMaterial({ color: cols[((i * 3 + Math.floor(a.x)) % cols.length + cols.length) % cols.length], side: THREE.DoubleSide, roughness: 0.9 })); m.position.set(a.x + (b.x - a.x) * t, a.y + 1.82 - h / 2, a.z + (b.z - a.z) * t); m.rotation.y = Math.atan2(b.x - a.x, b.z - a.z) + Math.PI / 2; m.castShadow = true; G.decor.add(m); }
  }
  [1, -1].forEach(sg => {
    const P = (x, y, z) => V(sg * x, y, sg * z);
    lanterns(P(20.3, 5.2, 27.8), P(-5, 3.0, 24.5), 0.6, 8);
    lanterns(P(-4, 4.6, 31), P(-15.5, 3.2, 31), 0.4, 5);
    laundry(P(-24.5, 2.6, 31), P(-17, 2.6, 33));
    laundry(P(-24.5, 2.6, 13), P(-18, 2.6, 15));
    laundry(P(-8, 2.0, 50), P(-2, 2.0, 51));
    laundry(P(19, 2.0, 50.5), P(25, 2.0, 49));
  });

  // ---------------- surroundings: building rows round the park, the tea house behind each spawn, canal continuing outside
  function building(x0, x1, z0, z1, h, face, variant) {
    const len = face === 'x' ? z1 - z0 : x1 - x0;
    const sideMat = mats['fac' + variant];
    const fm = [mats.plaster, mats.plaster, mats.terrace, mats.plaster, mats.plaster, mats.plaster];
    const idx = { '+x': 0, '-x': 1, '+z': 4, '-z': 5 };
    face.split(',').forEach(f => fm[idx[f]] = sideMat);
    const b = box(G.env, x0, x1, 0, h, z0, z1, fm); b.castShadow = h < 20;
    // AC units and a water tank on some roofs
    if (rnd() < 0.5) cyl(G.env, (x0 + x1) / 2 + rr(-1, 1), h, (z0 + z1) / 2 + rr(-1, 1), 0.7, 0.7, 1.4, mats.steel, 12);
  }
  const ring = [];
  for (let z = -ZH; z < ZH; z += 8) { if (z + 8 > CANAL.z0 && z < CANAL.z1) continue; ring.push(['+x', z]); ring.push(['-x', z]); }
  ring.forEach(([side, z], i) => {
    const za = Math.max(z, -ZH), zb = Math.min(z + 8, ZH); if (zb - za < 2) return;
    const v = (i * 5 + (side === '+x' ? 1 : 3)) % 8, h = 12.8 + (i % 3 === 0 ? 3.2 : 0);
    if (side === '+x') building(XH, XH + 10, za, zb, h, '-x', v); else building(-XH - 10, -XH, za, zb, h, '+x', v);
  });
  // the canal gaps in the rows: an outside street bridge across each exit
  [[1], [-1]].forEach(([sx]) => {
    const pts = [[4.5, 0], [0, 0.7], [-4.5, 0], [-3.5, 0], [-3.5, -1.8]];
    for (let i = 1; i < 20; i++) { const z = -3.5 + 7 * i / 20, u = z / 3.5; pts.push([z, -1.8 + 2.4 * Math.sqrt(1 - u * u)]); }
    pts.push([3.5, -1.8], [3.5, 0]);
    prism(G.env, pts, 'z', sx > 0 ? XH + 4 : -XH - 9, sx > 0 ? XH + 9 : -XH - 4, mats.stone);
    building(sx > 0 ? XH + 12 : -XH - 22, sx > 0 ? XH + 22 : -XH - 12, -12, -4.5, 9.6, sx > 0 ? '-x' : '+x', 2);
    building(sx > 0 ? XH + 12 : -XH - 22, sx > 0 ? XH + 22 : -XH - 12, 4.5, 12, 12.8, sx > 0 ? '-x' : '+x', 5);
  });
  // tea houses behind the spawn terraces, rows at the far ends
  [[1], [-1]].forEach(([s]) => {
    const z0 = s > 0 ? ZH : -ZH - 10, z1 = s > 0 ? ZH + 10 : -ZH;
    const b = box(G.env, -XH - 10, XH + 10, 0, 14, z0, z1, mats.plaster); b.castShadow = false;
    plane(G.env, 18, 12.8, mats.fac4, V(-s * 17, 6.4, s > 0 ? ZH - 0.02 : -ZH + 0.02), s > 0 ? Math.PI : 0);
    box(G.env, -XH - 10, XH + 10, 14, 14.4, z0 - 0.3, z1 + 0.3, mats.plasterW);
  });

  // old-town roofscape (instanced low houses, mostly pitched grey-tile roofs), thinning out with distance; the river side stays open
  {
    const houses = [], roofs = [], RIVER_X = 150, C = 11;
    for (let gx = -40; gx < 14; gx++) for (let gz = -40; gz < 40; gz++) {
      const x = gx * C + C / 2, z = gz * C + C / 2;
      if (x > RIVER_X - 14) continue;
      if (Math.abs(x) < XH + 24 && Math.abs(z) < ZH + 22) continue;
      if (Math.abs(z) < 9) continue;                                   // the canal keeps running out to the river
      if (gx % 6 === 0 || gz % 7 === 0) continue;                      // streets
      const d = Math.hypot(x, z); if (d > 430 || rnd() < 0.08 + d / 900) continue;
      const w = rr(7.5, 10.5), dd = rr(8.5, 10.5), h = rnd() < 0.86 ? rr(5, 11) : rr(14, 24);
      const px = x + rr(-0.6, 0.6), pz = z + rr(-0.6, 0.6);
      houses.push([px, pz, w, dd, h]); if (h < 13 && rnd() < 0.72) roofs.push([px, pz, w, dd, h]);
    }
    const hg = new THREE.BoxGeometry(1, 1, 1); hg.translate(0, 0.5, 0);
    const him = new THREE.InstancedMesh(hg, new THREE.MeshStandardMaterial({ roughness: 0.92 }), houses.length), o = new THREE.Object3D(), c = new THREE.Color();
    const pal = ['#e3d6b8', '#e2c4b9', '#e9e4d8', '#d4cfc4', '#c6d1d8', '#c7d8c9', '#c9c3b8', '#a96a55', '#d8cdb6'];
    houses.forEach(([x, z, w, d, h], i) => { o.position.set(x, 0, z); o.scale.set(w, h, d); o.rotation.set(0, 0, 0); o.updateMatrix(); him.setMatrixAt(i, o.matrix); him.setColorAt(i, c.set(pal[i % pal.length])); });
    him.receiveShadow = true; G.env.add(him);
    const rg = new THREE.ExtrudeGeometry(new THREE.Shape([new THREE.Vector2(-0.56, 0), new THREE.Vector2(0.56, 0), new THREE.Vector2(0, 0.4)]), { depth: 1, bevelEnabled: false }); rg.translate(0, 0, -0.5);
    const rim = new THREE.InstancedMesh(rg, new THREE.MeshStandardMaterial({ color: 0x666b70, roughness: 0.8 }), roofs.length);
    roofs.forEach(([x, z, w, d, h], i) => { o.position.set(x, h, z); o.scale.set(w, Math.min(w, 7) * 0.85, d + 0.6); o.updateMatrix(); rim.setMatrixAt(i, o.matrix); });
    G.env.add(rim);
    // a few wok-ear gables poking out of the roofscape
    const eg = new THREE.ExtrudeGeometry(new THREE.Shape([[-0.5, 0], [-0.55, 0.45], ...Array.from({ length: 13 }, (_, k) => { const a = Math.PI - k / 12 * Math.PI; return [Math.cos(a) * 0.55, 0.45 + Math.sin(a) * 0.55]; }), [0.5, 0]].map(([x, y]) => new THREE.Vector2(x, y))), { depth: 0.04, bevelEnabled: false });
    const ears = roofs.filter((_, i) => i % 9 === 0), eim = new THREE.InstancedMesh(eg, new THREE.MeshStandardMaterial({ color: 0x5b6166, roughness: 0.8 }), ears.length * 2);
    ears.forEach(([x, z, w, d, h], i) => [-1, 1].forEach((s, j) => { o.position.set(x, h, z + s * d / 2); o.scale.set(w, w * 0.55, w); o.updateMatrix(); eim.setMatrixAt(i * 2 + j, o.matrix); }));
    G.env.add(eim);
  }
  // the Pearl River to the east, the new-town skyline and the tower on the far bank, Baiyun hills to the north-west
  {
    const river = new THREE.Mesh(new THREE.PlaneGeometry(520, 9000), new THREE.MeshStandardMaterial({ color: 0x7d9f9b, roughness: 0.15, metalness: 0.25 }));
    river.rotation.x = -Math.PI / 2; river.position.set(150 + 260, -1.2, 0); G.env.add(river);
    box(G.env, 140, 152, -1.2, 0.3, -4500, 4500, mats.stone, { cast: false }); box(G.env, 668, 690, -1.2, 0.3, -4500, 4500, mats.stone, { cast: false });
    const far = new THREE.Mesh(new THREE.PlaneGeometry(4000, 9000), new THREE.MeshStandardMaterial({ color: 0xcfc9bd, roughness: 1 })); far.rotation.x = -Math.PI / 2; far.position.set(690 + 2000, 0, 0); G.env.add(far);
    const sky = [], o = new THREE.Object3D(), c = new THREE.Color();
    for (let i = 0; i < 240; i++) {
      const x = rr(760, 1900), z = rr(-3600, 600), dc = Math.hypot(x - 1000, (z + 1700) * 0.7);
      const h = Math.max(40, rr(60, 330) * Math.max(0.35, 1.3 - dc / 1400)); sky.push([x, z, rr(28, 60), rr(28, 60), h]);
    }
    const sim = new THREE.InstancedMesh(new THREE.BoxGeometry(1, 1, 1).translate(0, 0.5, 0), new THREE.MeshStandardMaterial({ roughness: 0.3, metalness: 0.55 }), sky.length);
    sky.forEach(([x, z, w, d, h], i) => { o.position.set(x, 0, z); o.scale.set(w, h, d); o.rotation.y = rr(-0.2, 0.2); o.updateMatrix(); sim.setMatrixAt(i, o.matrix); sim.setColorAt(i, c.set(['#a6b7c6', '#bfcad2', '#93a7b8', '#cfd3d4', '#b3bcc0'][i % 5])); });
    G.env.add(sim);
    // the tower: a twisted hyperboloid lattice round a core, mast on top (≈600 m)
    const tw = new THREE.Group(); tw.position.set(980, 0, -1900); G.env.add(tw);
    const tm = new THREE.MeshStandardMaterial({ color: 0xece8e0, roughness: 0.45, metalness: 0.35 });
    const N = 24, sm = new THREE.InstancedMesh(new THREE.CylinderGeometry(1.8, 1.8, 1, 5).translate(0, 0.5, 0), tm, N * 2);
    for (let i = 0; i < N * 2; i++) {
      const a0 = i % N / N * Math.PI * 2, tw2 = i < N ? 1.7 : -1.7;
      const p0 = V(Math.cos(a0) * 80, 0, Math.sin(a0) * 55), p1 = V(Math.cos(a0 + tw2) * 27, 454, Math.sin(a0 + tw2) * 20);
      const d = p1.clone().sub(p0); o.position.copy(p0); o.quaternion.setFromUnitVectors(V(0, 1, 0), d.clone().normalize()); o.scale.set(1, d.length(), 1); o.updateMatrix(); sm.setMatrixAt(i, o.matrix);
    }
    tw.add(sm);
    tw.add(new THREE.Mesh(new THREE.CylinderGeometry(15, 18, 454, 18).translate(0, 227, 0), tm));
    // waist rings follow the narrowing lattice
    for (let k = 1; k <= 9; k++) {
      const y = k * 45.4, t = y / 454; let ra = 0, rb = 0;
      for (let j = 0; j < 64; j++) { const a0 = j / 64 * Math.PI * 2; const px = Math.cos(a0) * 80 * (1 - t) + Math.cos(a0 + 1.7) * 27 * t, pz = Math.sin(a0) * 55 * (1 - t) + Math.sin(a0 + 1.7) * 20 * t; ra = Math.max(ra, Math.abs(px)); rb = Math.max(rb, Math.abs(pz)); }
      const r = new THREE.Mesh(new THREE.TorusGeometry(1, 0.03, 4, 48), tm); r.scale.set(ra, rb, 60); r.rotation.x = Math.PI / 2; r.position.y = y; tw.add(r);
    }
    tw.add(new THREE.Mesh(new THREE.CylinderGeometry(1.5, 8, 146, 8).translate(0, 454 + 73, 0), tm));
    tw.rotation.y = 0.5;
    // hills
    const hm = new THREE.MeshStandardMaterial({ color: 0x86a08e, roughness: 1, flatShading: true });
    [[-1900, -1500, 650, 300], [-2400, -500, 850, 360], [-2300, 700, 700, 240], [-1500, -2500, 600, 220], [-900, 2400, 700, 200]].forEach(([x, z, r, h]) => { const g = new THREE.IcosahedronGeometry(1, 2); g.scale(r, h, r * 0.8); const m = new THREE.Mesh(g, hm); m.position.set(x, -30, z); G.env.add(m); });
  }
  rootG.traverse(o => { if (o.isMesh) (Array.isArray(o.material) ? o.material : [o.material]).forEach(m => { if (m && 'envMapIntensity' in m) m.envMapIntensity = 0; }); });
  return { root: rootG, G, mats };
}
